### ISSUE TITLE
Error: LinkageError occurred while loading main class  java.lang.ClassFormatError: Incompatible magic value

### ISSUE THREAD

**Issue by hetykai** [Col-E/Recaf#127]
Hello, thank you for writing such a good program. But I don't know if I did anything wrong, I just wrote a Hello world:
```
package loc.kaitest.main;
public class MainTest {
	public static void main(String[] args) {
		System.out.println("hello,world!");
	}
}
```
,and compiled it into a class file, then opened it with Recaf and changed it to "hello,earth.". But the final class file didn't perform successfully, i run it in cmd with `java loc\kaitest\main\MainTest`, it reported the following error:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.ClassFormatError: Incompatible magic value 1347093252 in class file loc\kaitest\main\MainTest
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```
I run this with jdk8 on win10.
Then I run it in wsl(ubuntu) with jdk11, it report the following errors:
```
Error: LinkageError occurred while loading main class loc.kaitest.main.MainTest
        java.lang.ClassFormatError: Incompatible magic value 1347093252 in class file loc/kaitest/main/MainTest
```

**Comment by hetykai** [comment]
I found out where I was wrong, and I thought it would be a class file to open the class file with RECAF and export it, but in fact it exported a jar file.

**Comment by Col-E** [comment]
Oops, I'll change it so that a class exports as a class. It would make more sense.
