### ISSUE TITLE
Unable to auto patch recaf on JDK 12

### ISSUE THREAD

**Issue by artemking4-Projects** [Col-E/Recaf#132]
**Auto patch in recaf just gives me a error**

`C:\Program Files\Java\jdk-12.0.1\bin>java.exe -jar recaf.jar
Detected JDK 11+ without OpenJFX dependencies
Dependencies will be downloaded and Recaf will restart...
java.util.UnknownFormatConversionException: Conversion = 'F'
        at java.base/java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2839)
        at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2865)
        at java.base/java.util.Formatter.parse(Formatter.java:2713)
        at java.base/java.util.Formatter.format(Formatter.java:2655)
        at java.base/java.util.Formatter.format(Formatter.java:2609)
        at java.base/java.lang.String.format(String.java:2988)
        at me.coley.recaf.util.Updater.generatePatched(Updater.java:145)
        at me.coley.recaf.util.Updater.updateViaJdk11Patch(Updater.java:107)
        at me.coley.recaf.util.Dependencies.check(Dependencies.java:49)
        at me.coley.recaf.Recaf.main(Recaf.java:13)
java.util.UnknownFormatConversionException: Conversion = 'F'`

**Comment by Col-E** [comment]
Can you try again using this? This build should include some more useful debug information. I can't reproduce this on my own machine.

[recaf-1.15.1-debug.jar.zip](https://github.com/Col-E/Recaf/files/3292912/recaf-1.15.1-debug.jar.zip)

**Comment by artemking4-Projects** [comment]
So i have ran this file as admin in javaw.exe and i see that it only made a file called recaf-1.15.1-patched.jar. But it is empty

**Comment by Col-E** [comment]
But can you please tell me what the console logs said?

**Comment by Col-E** [comment]
You probably ran Recaf in working-directory that had a space or some special character in it. Then because of [URL encoding](https://www.w3schools.com/tags/ref_urlencode.asp) Recaf failed to use the path in `String.format`.
