### ISSUE TITLE
Make a new release please

### ISSUE THREAD

**Issue by artemking4-Projects** [Col-E/Recaf#148]
Compile a jar and release it please, cannot do this on my machine. Maven gives me that:
```C:\Program Files (x86)\Steam\steamapps\common\BrainOut\Recaf-master>mvn package -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------------< me.coley:recaf >---------------------------
[INFO] Building Recaf 1.15.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ recaf ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ recaf ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 65 resources to resources/
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ recaf ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ recaf ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ recaf ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ recaf ---
[INFO] Surefire report directory: C:\Program Files (x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\surefire-reports
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running me.coley.recaf.AssemblerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.215 s - in me.coley.recaf.AssemblerTest
[INFO] Running me.coley.recaf.FormatFactoryTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.233 s - in me.coley.recaf.FormatFactoryTest
[INFO] Running me.coley.recaf.GraphTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.03 s - in me.coley.recaf.GraphTest
[INFO] Running me.coley.recaf.HierarchyTest
[ERROR] Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.052 s <<< FAILURE! - in me.coley.recaf.HierarchyTest
[ERROR] testParentToChildSearch  Time elapsed: 0.037 s  <<< ERROR!
java.nio.file.NoSuchFileException: C:\Program%20Files%20(x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\test-classes\inherit.jar
        at me.coley.recaf.HierarchyTest.setup(HierarchyTest.java:27)

[ERROR] testParents  Time elapsed: 0 s  <<< ERROR!
java.nio.file.NoSuchFileException: C:\Program%20Files%20(x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\test-classes\inherit.jar
        at me.coley.recaf.HierarchyTest.setup(HierarchyTest.java:27)

[ERROR] testDescendants  Time elapsed: 0.002 s  <<< ERROR!
java.nio.file.NoSuchFileException: C:\Program%20Files%20(x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\test-classes\inherit.jar
        at me.coley.recaf.HierarchyTest.setup(HierarchyTest.java:27)

[ERROR] testHierarchyBuilder  Time elapsed: 0.001 s  <<< ERROR!
java.nio.file.NoSuchFileException: C:\Program%20Files%20(x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\test-classes\inherit.jar
        at me.coley.recaf.HierarchyTest.setup(HierarchyTest.java:27)

[ERROR] testIsLibrary  Time elapsed: 0.001 s  <<< ERROR!
java.nio.file.NoSuchFileException: C:\Program%20Files%20(x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\test-classes\inherit.jar
        at me.coley.recaf.HierarchyTest.setup(HierarchyTest.java:27)

[ERROR] testChildToParentSearch  Time elapsed: 0.002 s  <<< ERROR!
java.nio.file.NoSuchFileException: C:\Program%20Files%20(x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\test-classes\inherit.jar
        at me.coley.recaf.HierarchyTest.setup(HierarchyTest.java:27)

[INFO] Running me.coley.recaf.InputTest
[ERROR] Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.002 s <<< FAILURE! - in me.coley.recaf.InputTest
[ERROR] testClassRename  Time elapsed: 0 s  <<< ERROR!
java.nio.file.NoSuchFileException: C:\Program%20Files%20(x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\test-classes\inherit.jar
        at me.coley.recaf.InputTest.setup(InputTest.java:30)

[ERROR] testEntrySet  Time elapsed: 0 s  <<< ERROR!
java.nio.file.NoSuchFileException: C:\Program%20Files%20(x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\test-classes\inherit.jar
        at me.coley.recaf.InputTest.setup(InputTest.java:30)

[ERROR] testSize  Time elapsed: 0 s  <<< ERROR!
java.nio.file.NoSuchFileException: C:\Program%20Files%20(x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\test-classes\inherit.jar
        at me.coley.recaf.InputTest.setup(InputTest.java:30)

[ERROR] testCacheInvalidation  Time elapsed: 0 s  <<< ERROR!
java.nio.file.NoSuchFileException: C:\Program%20Files%20(x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\test-classes\inherit.jar
        at me.coley.recaf.InputTest.setup(InputTest.java:30)

[ERROR] testMethodRename  Time elapsed: 0 s  <<< ERROR!
java.nio.file.NoSuchFileException: C:\Program%20Files%20(x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\test-classes\inherit.jar
        at me.coley.recaf.InputTest.setup(InputTest.java:30)

[ERROR] testGetEquality  Time elapsed: 0 s  <<< ERROR!
java.nio.file.NoSuchFileException: C:\Program%20Files%20(x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\test-classes\inherit.jar
        at me.coley.recaf.InputTest.setup(InputTest.java:30)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   HierarchyTest.setup:27 ? NoSuchFile C:\Program%20Files%20(x86)\Steam\steamapps...
[ERROR]   HierarchyTest.setup:27 ? NoSuchFile C:\Program%20Files%20(x86)\Steam\steamapps...
[ERROR]   HierarchyTest.setup:27 ? NoSuchFile C:\Program%20Files%20(x86)\Steam\steamapps...
[ERROR]   HierarchyTest.setup:27 ? NoSuchFile C:\Program%20Files%20(x86)\Steam\steamapps...
[ERROR]   HierarchyTest.setup:27 ? NoSuchFile C:\Program%20Files%20(x86)\Steam\steamapps...
[ERROR]   HierarchyTest.setup:27 ? NoSuchFile C:\Program%20Files%20(x86)\Steam\steamapps...
[ERROR]   InputTest.setup:30 ? NoSuchFile C:\Program%20Files%20(x86)\Steam\steamapps\com...
[ERROR]   InputTest.setup:30 ? NoSuchFile C:\Program%20Files%20(x86)\Steam\steamapps\com...
[ERROR]   InputTest.setup:30 ? NoSuchFile C:\Program%20Files%20(x86)\Steam\steamapps\com...
[ERROR]   InputTest.setup:30 ? NoSuchFile C:\Program%20Files%20(x86)\Steam\steamapps\com...
[ERROR]   InputTest.setup:30 ? NoSuchFile C:\Program%20Files%20(x86)\Steam\steamapps\com...
[ERROR]   InputTest.setup:30 ? NoSuchFile C:\Program%20Files%20(x86)\Steam\steamapps\com...
[INFO]
[ERROR] Tests run: 27, Failures: 0, Errors: 12, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.963 s
[INFO] Finished at: 2019-06-25T00:29:11+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project recaf: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Program Files (x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project recaf: There are test failures.

Please refer to C:\Program Files (x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to C:\Program Files (x86)\Steam\steamapps\common\BrainOut\Recaf-master\target\surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
    at org.apache.maven.plugin.surefire.SurefireHelper.throwException (SurefireHelper.java:271)
    at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:159)
    at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:373)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:1018)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:848)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by Col-E** [comment]
Actually this was rather helpful. Didn't know that the test classes failed like this. Fixed! 

`mvn clean package` should work again. I'll make a build after a few changes, I'm just a bit busy right now.

**Comment by artemking4-Projects** [comment]
New error
```[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Program Files (x86)/Steam/steamapps/common/BrainOut/Recaf-master/src/main/java/me/coley/recaf/Input.java:[509,32] incompatible types: java.lang.instrument.ClassFileTransformer is not a functional interface
    no abstract method found in interface java.lang.instrument.ClassFileTransformer
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.304 s
[INFO] Finished at: 2019-06-25T11:43:24+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project recaf: Compilation failure
[ERROR] /C:/Program Files (x86)/Steam/steamapps/common/BrainOut/Recaf-master/src/main/java/me/coley/recaf/Input.java:[509,32] incompatible types: java.lang.instrument.ClassFileTransformer is not a functional interface
[ERROR]     no abstract method found in interface java.lang.instrument.ClassFileTransformer
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by andylizi** [comment]
What's your Java version?

**Comment by artemking4-Projects** [comment]
Tried JDK 12, JDK 11, JDK 1.8.0

**Comment by andylizi** [comment]
...Weird. It says there're not any methods in `java.lang.instrument.ClassFileTransformer` interface, but in fact it does :confused:. I'm at a loss as to what could've caused this.

**Comment by Col-E** [comment]
This is the expected method descriptor in `java.lang.instrument.ClassFileTransformer`
```java
byte[]
    transform(  ClassLoader         loader,
                String              className,
                Class<?>            classBeingRedefined,
                ProtectionDomain    protectionDomain,
                byte[]              classfileBuffer)
```

* In [Java 8](https://docs.oracle.com/javase/7/docs/api/java/lang/instrument/ClassFileTransformer.html) it is the only method in the class.
* In [Java 9+](https://docs.oracle.com/javase/9/docs/api/java/lang/instrument/ClassFileTransformer.html) it has two methods. The one above  and a new one which also takes `java.lang.Module` as a parameter.

The java compiler should be able to recognize from the way we structured the lambda that it refers to the one shown above.

```java
instrumentation.addTransformer(
        (loader, className, classBeingRedefined, domain, classfileBuffer) -> { /* ... */ },
        true);
```

When I compile using JDK 8 and 12 it succeeds for me both times. Not sure what's going on here.

**Comment by Col-E** [comment]
I'm not ready to post an update just yet, but since I have no idea how to resolve this new error, I'll drop the current build here:

[recaf-1.15.5-update.jar.zip](https://github.com/Col-E/Recaf/files/3324900/recaf-1.15.5-update.jar.zip)

**Comment by Col-E** [comment]
Can you try replacing `src\main\java\me\coley\recaf\Input.java` with the following 
[Input.java.zip](https://github.com/Col-E/Recaf/files/3324926/Input.java.zip), then try compiling again?

**Comment by artemking4-Projects** [comment]
Ok, let me try

**Comment by artemking4-Projects** [comment]
This worked

**Comment by Col-E** [comment]
Welp, thats odd but hey, it works.
