### ISSUE TITLE
AutoUpdater fails with HTTP code 501

### ISSUE THREAD

**Issue by Earthcomputer** [Col-E/Recaf#175]
**Describe the bug**
Accessing maven central through HTTP rather than HTTPS is returning response code 501, causing the program to crash and not to launch.

**To Reproduce**
1. Launch the program

**Screenshots**
```
Detected JDK 11+ without OpenJFX dependencies
Dependencies will be downloaded and Recaf will restart...
java.io.IOException: Server returned HTTP response code: 501 for URL: http://central.maven.org/maven2/org/controlsfx/controlsfx/11.0.0/controlsfx-11.0.0.jar
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1919)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/java.net.URL.openStream(URL.java:1139)
	at me.coley.recaf.util.Updater.generatePatched(Updater.java:153)
	at me.coley.recaf.util.Updater.updateViaJdk11Patch(Updater.java:107)
	at me.coley.recaf.util.Dependencies.check(Dependencies.java:49)
	at me.coley.recaf.Recaf.main(Recaf.java:23)
java.io.IOException: Server returned HTTP response code: 501 for URL: http://central.maven.org/maven2/org/controlsfx/controlsfx/11.0.0/controlsfx-11.0.0.jar
Rerunning
```

**Comment by Col-E** [comment]
Somebody wrote about potential MITM for maven artifacts so central now denies HTTPS, fun stuff.

**Comment by Col-E** [comment]
In hindsight, should have gotten this fixed BEFORE they started dishing out 501's... now Java 11+ users will have to get [`1.15.9`](https://github.com/Col-E/Recaf/tree/1.15.9) manually if they haven't already run Recaf _(Which will have saved a version with the required libs)_
