### ISSUE TITLE
recaf-bin-1.15.10: no jfxwebkit in java.library.path

### ISSUE THREAD

**Issue by blshkv** [Col-E/Recaf#187]
the previous version 1.15.9 was running fine
my env:
dev-java/openjdk-11.0.5_p10
dev-java/openjfx-11.0.3_p1

the stacktrace:

```
bash$ recaf 

Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.coley.recaf.util.Classpath$ClassPathScanner (file:/data/opt/recaf/recaf.jar) to field java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP
WARNING: Please consider reporting this to the maintainers of me.coley.recaf.util.Classpath$ClassPathScanner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

(java:3613): Gdk-WARNING **: 09:01:57.008: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsatisfiedLinkError: no jfxwebkit in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
        at java.base/java.lang.System.loadLibrary(System.java:1870)
        at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:150)
        at javafx.graphics/com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:52)
        at javafx.web/com.sun.webkit.WebPage.lambda$static$0(WebPage.java:133)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.web/com.sun.webkit.WebPage.<clinit>(WebPage.java:132)
        at javafx.web/javafx.scene.web.WebEngine.<init>(WebEngine.java:841)
        at javafx.web/javafx.scene.web.WebEngine.<init>(WebEngine.java:826)
        at javafx.web/javafx.scene.web.WebView.<init>(WebView.java:260)
        at me.coley.recaf.ui.component.UpdatePrompt.consent(UpdatePrompt.java:27)
        at me.coley.recaf.util.Updater.updateFromRelease(Updater.java:60)
        at me.coley.recaf.InitListener.onInit(InitListener.java:41)
        at me.coley.event.EventBus$InvokeWrapper.invoke(EventBus.java:488)
        at me.coley.event.EventBus$Handler.post(EventBus.java:290)
        at me.coley.event.EventBus.post(EventBus.java:102)
        at me.coley.event.Bus.post(Bus.java:65)
        at me.coley.recaf.ui.FxWindow.start(FxWindow.java:174)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        ... 1 more

```

**Comment by blshkv** [comment]
after some digging, I found out that openjfx is compiled without webkit (COMPILE_WEBKIT = false).
Can you double check if it is really required before I filed an upstream bug report please?

**Comment by blshkv** [comment]
The difference between two releases is very minor (see https://github.com/Col-E/Recaf/compare/1.15.9...master)

Perhaps, something changed in the compiling process? Could you please review it?

**Comment by Col-E** [comment]
> Can you double check if it is really required

Required in Recaf? Currently WebView is only used to display the update log _(With the proper formatting of markdown headers and lists)_

> Perhaps, something changed in the compiling process?

When I push a release all I do is run `mvn package` and drop the output jar on github. I've not changed my local maven installation or touched the project `pom.xml`. 

Its also unlikely but maybe it has something to do with the JDK 11+ patch process? The URL's all work when I paste them into my browser _(Such as the [JFX web dependency](https://repo1.maven.org/maven2/org/openjfx/javafx-web/11.0.2/))_. On the linux version the native library that is _"missing"_ in your error should be bundled in there.

**Comment by blshkv** [comment]
Funny enough, I'm unable to reproduce it anymore. It might be something to do with a recent upgrade.
Sorry, ignore this report.
