### ISSUE TITLE
2.0.0-redesign.7 NoClassDefFoundError

### ISSUE THREAD

**Issue by Enaium** [Col-E/Recaf#202]
```
Exception in thread "main" java.lang.NoClassDefFoundError: me/coley/recaf/ui/component/ReflectivePropertySheet
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at me.coley.recaf.plugin.PluginFolderSource.load(PluginFolderSource.java:69)
        at org.plugface.core.impl.DefaultPluginManager.loadPlugins(DefaultPluginManager.java:105)
        at me.coley.recaf.plugin.PluginsManager.load(PluginsManager.java:54)
        at me.coley.recaf.Recaf.main(Recaf.java:55)
Caused by: java.lang.ClassNotFoundException: me.coley.recaf.ui.component.ReflectivePropertySheet
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 17 more
```

**Comment by Col-E** [comment]
Looks like your plugin depends on classes from Recaf 1.15.

This won't work in 2.0.0

**Comment by Col-E** [comment]
However the exception handling should catch `Throwable` and not `Exception` just to be safe.

**Comment by Col-E** [comment]
Closing as its not an issue internal to Recaf.
