### ISSUE TITLE
Java 14+ fails when recompiling deprecated Java 5 classes

### ISSUE THREAD

**Issue by Col-E** [Col-E/Recaf#261]
**Describe the bug**

> The recompile feature breaks on Java 14+ when attempting to recompile a class compiled in Java 5 or below. Recaf attempts to intelligently use the compiler version the class was generated with, but this does not work when that version is deprecated...

**To Reproduce**

1. Open [sample.jar](https://github.com/Col-E/Recaf/files/5159553/sample.jar.zip)  - Rename to `jar` extension
2. Make any valid change to the class  `Main` in decompile mode
3. Try to save
4. Check log file

**Exception**

```
java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: begin -2, end 28994, length 28994
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:163)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
        at me.coley.recaf.compiler.JavacCompiler.compile(JavacCompiler.java:51)
        at me.coley.recaf.ui.controls.text.JavaEditorPane.save(JavaEditorPane.java:96)
        at me.coley.recaf.ui.controls.view.ClassViewport.save(ClassViewport.java:201)
        at me.coley.recaf.ui.controls.view.EditorViewport.handleKeyReleased(EditorViewport.java:53)
        at me.coley.recaf.ui.controls.view.ClassViewport.handleKeyReleased(ClassViewport.java:51)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$KeyHandler.process(Scene.java:4098)
        at javafx.scene.Scene.processKeyEvent(Scene.java:2157)
        at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2625)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
        at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
        at com.sun.glass.ui.View.notifyKey(View.java:971)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.StringIndexOutOfBoundsException: begin -2, end 28994, length 28994
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3756)
        at java.base/java.lang.String.substring(String.java:1902)
        at java.base/java.lang.String.substring(String.java:1875)
        at me.coley.recaf.ui.controls.text.JavaErrorHandling.report(JavaErrorHandling.java:43)
        at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedDiagnosticListener.report(ClientCodeWrapper.java:772)
        at jdk.compiler/com.sun.tools.javac.util.Log.writeDiagnostic(Log.java:755)
        at jdk.compiler/com.sun.tools.javac.util.Log$DefaultDiagnosticHandler.report(Log.java:736)
        at jdk.compiler/com.sun.tools.javac.util.Log.report(Log.java:694)
        at jdk.compiler/com.sun.tools.javac.util.AbstractLog.error(AbstractLog.java:107)
        at jdk.compiler/com.sun.tools.javac.main.Arguments.validate(Arguments.java:581)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:189)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:101)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
        ... 38 more
```

**Comment by Col-E** [comment]
Will be fixed in `2.6.0`
