### ISSUE TITLE
JFX version

### ISSUE THREAD

**Issue by antichown** [Col-E/Recaf#300]
linux@root:~/Desktop/LinuxDecompiler$  java -jar recaf2.jar 
02:19:59.231 [main] INFO : Missing JavaFX dependencies, attempting to patch in missing classes
02:19:59.233 [main] INFO :  - No local cache, downloading dependencies...
Exception in thread "main" java.lang.AssertionError: Failed to get latest supported JFX version
	at me.coley.recaf.util.self.SelfDependencyPatcher.getLatestSupportedJfxVersion(SelfDependencyPatcher.java:221)
	at me.coley.recaf.util.self.SelfDependencyPatcher.getLatestDependencies(SelfDependencyPatcher.java:228)
	at me.coley.recaf.util.self.SelfDependencyPatcher.fetchDependencies(SelfDependencyPatcher.java:169)
	at me.coley.recaf.util.self.SelfDependencyPatcher.patch(SelfDependencyPatcher.java:76)
	at me.coley.recaf.Recaf.init(Recaf.java:81)
	at me.coley.recaf.Recaf.main(Recaf.java:49)

--------------------------------------------

other file
no main manifest attribute, in recaf2.jar

**Comment by Col-E** [comment]
What version of Java are you using?

**Comment by antichown** [comment]
I was using java 8 when I upgraded to version 11, the problem was fixed 

thanx

**Comment by Col-E** [comment]
👍
