### ISSUE TITLE
null pointer exception when passing argument

### ISSUE THREAD

**Issue by maxandersen** [Col-E/Recaf#313]
**Describe the bug**

giving a argument to the .jar results in NPE.

**To Reproduce**

1. `jbang https://github.com/Col-E/Recaf/releases/download/2.16.6/recaf-2.16.6-J8-jar-with-dependencies.jar my.jar`

**Exception**

If applicable, add the exception/stacktrace.
```
Exception in thread "main" java.lang.NullPointerException
	at me.coley.recaf.util.self.SelfUpdater.shouldSkipUpdate(SelfUpdater.java:146)
	at me.coley.recaf.util.self.SelfUpdater.checkForUpdates(SelfUpdater.java:61)
	at me.coley.recaf.Recaf.launch(Recaf.java:103)
	at me.coley.recaf.Recaf.main(Recaf.java:51)
```

**Screenshots**

**Comment by Col-E** [comment]
Hmmm thats interesting. If you exclude the `myJar.jar` argument for the initial workspace file it doesn't occur.

**Comment by Col-E** [comment]
Oh right its been forever since I looked at this command.

```java
@Option(names = {"--input" }, description = "The input file to load. " +
			"Supported types are: class, jar, json")
	public Path input;
```

You specify an input as an option, not as an indexed parameter
