### ISSUE TITLE
100% CPU usage opening a specific jar

### ISSUE THREAD

**Issue by bubbleguuum** [Col-E/Recaf#341]
Version: 2.17.2 (fatjar), running on Linux 

java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-suse-1.1-x8664)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-suse-1.1-x8664, mixed mode)

**Describe the bug**

Opening charm-glisten-6.0.6.jar results in 100% CPU usage forever.
This does not happen with other jars I tested.

**To Reproduce**

1. fetch https://nexus.gluonhq.com/nexus/content/repositories/releases/com/gluonhq/charm-glisten/6.0.6/charm-glisten-6.0.6.jar
2. open jar in recaf
3. wait a few seconds to see CPU usage rise to 100% and staying there.

**Comment by x4e** [comment]
I think the issue is from JPhantom making the phantom classes.
```Java
"ForkJoinPool-1-worker-7" #31 daemon prio=5 os_prio=0 cpu=56865.45ms elapsed=57.36s tid=0x00007fc08c0e6dd0 nid=0x109df runnable  [0x00007fc03dedc000]
   java.lang.Thread.State: RUNNABLE
	at org.objectweb.asm.Type.hashCode(Type.java:879)
	at java.util.HashMap.hash(java.base@15.0.1/HashMap.java:340)
	at java.util.HashMap.getNode(java.base@15.0.1/HashMap.java:570)
	at java.util.HashMap.containsKey(java.base@15.0.1/HashMap.java:596)
	at java.util.LinkedHashMap$LinkedKeySet.contains(java.base@15.0.1/LinkedHashMap.java:566)
	at org.jgrapht.graph.AbstractBaseGraph.containsVertex(AbstractBaseGraph.java:304)
	at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:127)
	at org.jgrapht.graph.AbstractBaseGraph.outgoingEdgesOf(AbstractBaseGraph.java:391)
	at org.clyze.jphantom.constraints.solvers.SingleInheritanceSolver.createSubgraph(SingleInheritanceSolver.java:60)
	at org.clyze.jphantom.constraints.solvers.SingleInheritanceSolver.getComponent(SingleInheritanceSolver.java:46)
	at org.clyze.jphantom.constraints.solvers.SingleInheritanceSolver.placeUnder(SingleInheritanceSolver.java:100)
	at org.clyze.jphantom.constraints.solvers.SingleInheritanceSolver.placeUnder(SingleInheritanceSolver.java:112)
	at org.clyze.jphantom.constraints.solvers.SingleInheritanceSolver.solve(SingleInheritanceSolver.java:130)
	at org.clyze.jphantom.constraints.solvers.AbstractSolver.solve(AbstractSolver.java:54)
	at org.clyze.jphantom.constraints.solvers.SingleInheritanceSolver.solve(SingleInheritanceSolver.java:124)
	at org.clyze.jphantom.constraints.solvers.BasicSolver.solveClassGraph(BasicSolver.java:226)
	at org.clyze.jphantom.constraints.solvers.InterfaceSolver.solve(InterfaceSolver.java:134)
	at org.clyze.jphantom.constraints.solvers.AbstractSolver.solve(AbstractSolver.java:54)
	at org.clyze.jphantom.constraints.solvers.InterfaceSolver.solve(InterfaceSolver.java:66)
	at org.clyze.jphantom.constraints.solvers.BasicSolver.solve(BasicSolver.java:147)
	at org.clyze.jphantom.constraints.solvers.BasicSolver.solve(BasicSolver.java:13)
	at org.clyze.jphantom.constraints.solvers.ForwardingSolver.solve(ForwardingSolver.java:36)
	at org.clyze.jphantom.constraints.solvers.ForwardingSolver.solve(ForwardingSolver.java:36)
	at org.clyze.jphantom.constraints.solvers.PruningSolver.solve(PruningSolver.java:19)
	at org.clyze.jphantom.JPhantom.run(JPhantom.java:95)
	at me.coley.recaf.workspace.PhantomResource.populatePhantoms(PhantomResource.java:120)
	at me.coley.recaf.workspace.Workspace.lambda$analyzePhantoms$2(Workspace.java:192)
	at me.coley.recaf.workspace.Workspace$$Lambda$518/0x0000000800e1fcb0.run(Unknown Source)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(java.base@15.0.1/ForkJoinTask.java:1409)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@15.0.1/ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@15.0.1/ForkJoinPool.java:1016)
	at java.util.concurrent.ForkJoinPool.scan(java.base@15.0.1/ForkJoinPool.java:1665)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@15.0.1/ForkJoinPool.java:1598)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@15.0.1/ForkJoinWorkerThread.java:183)
```

**Comment by Col-E** [comment]
For now, go into the config menu and disable class generation while working on this jar.

I'll look into the performance issue in a bit.

**Comment by Col-E** [comment]
Confirmed, it is a side effect of some optimizations I made to phantom generation. Working on a fix now.

**Comment by Col-E** [comment]
Jitpack seems to be down but once it publishes the updated artifact I can push a fix release.
