### ISSUE TITLE
StringIndexOutOfBoundsException in CfrDecompiler.clean

### ISSUE THREAD

**Issue by shoffmeister** [Col-E/Recaf#344]
Upon decompiling a specific class in Recaf 2.17.3 with CFR, the Recaf CFR decompiler _integration_ (not the decompiler itself) runs into "java.lang.StringIndexOutOfBoundsException"

**To Reproduce**

* Download the JAR for https://mvnrepository.com/artifact/com.google.code.gson/gson/2.2.4 (https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar)
* File -> Load -> gson-2.2.4.jar
* Decompile class "com/google/gson/internal/$Gson$Types$GenericArrayTypeImpl"

//exp: decompiles successfully
//act: java.lang.StringIndexOutOfBoundsException

**Exception**

From console output:
```
08:38:40.837 [pool-6-thread-3] ERROR: Class failed to decompiled: com/google/gson/internal/$Gson$Types$GenericArrayTypeImpl
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at me.coley.recaf.decompile.cfr.CfrDecompiler.clean(CfrDecompiler.java:93)
        at me.coley.recaf.decompile.cfr.CfrDecompiler.decompile(CfrDecompiler.java:64)
        at me.coley.plugin.decompile.DecompilePanel.lambda$startDecompile$2(DecompilePanel.java:78)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
i.e. the crash is not in CFR (which I validated to decompile), but in the integration of CFR at https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/decompile/cfr/CfrDecompiler.java#L93

**Comment by shoffmeister** [comment]
This is not limited to this specific .jar, but apparently a more generic problem.

In a larger context, I get quite a few of these exceptions (with the same stack trace) which would suggest that this is a more general problem. Alas, I do not understand what clean() is trying to accomplish, so I cannot really contribute more constructive feedback at this time.

**Comment by TimmyOVO** [comment]
Can confirm that, i will try to fix this later.

**Comment by Col-E** [comment]
```java
private static final ThreadLocal<DecompilerContext> currentContext = new ThreadLocal();
```

This sorta stuff is just... 🙄 why you gotta do this FF? Fix was to wrap the crashing bit with `synchronized(this)`
