### ISSUE TITLE
Run on java11

### ISSUE THREAD

**Issue by LovesAsuna** [Col-E/Recaf#350]
**Describe the bug**

> A clear and concise description of what the bug is.
When I upgrade to java11, the following exception will be thrown

21:40:05.786 [main] INFO : Missing JavaFX dependencies, attempting to patch in missing classes
21:40:05.788 [main] INFO :  - Local cache found!
21:40:05.788 [main] INFO :  - Loading dependencies...
21:40:05.791 [main] INFO :  - Done!
21:40:05.791 [main] INFO : Recaf-2.17.4
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task
        at me.coley.recaf.command.impl.Initializer.run(Initializer.java:60)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at me.coley.recaf.Recaf.launch(Recaf.java:98)
        at me.coley.recaf.Recaf.main(Recaf.java:51)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 10 more

**Comment by Col-E** [comment]
Should work up to the latest version of Java.

What OS/Jvm information can you provide?

**Comment by Col-E** [comment]
```
"C:\Program Files\AdoptOpenJDK\jdk-16\bin\java.exe" -jar recaf-2.17.4-J8-jar-with-dependencies.jar
19:18:59.876 [main] WARN : Failed to delete old log file, will append instead
19:18:59.878 [main] INFO : Missing JavaFX dependencies, attempting to patch in missing classes
19:18:59.879 [main] INFO :  - Local cache found!
19:18:59.879 [main] INFO :  - Loading dependencies...
19:18:59.884 [main] INFO :  - Done!
19:18:59.884 [main] INFO : Recaf-2.17.4
19:18:59.987 [main] TRACE: Loading configuration
19:19:00.153 [main] INFO : Discovered plugin 'Decompile All-1.1.0'
19:19:00.154 [main] INFO : Discovered plugin 'Theme Editor-1.0.0'
19:19:00.154 [main] INFO : Loaded 2 plugins
19:19:02.949 [JavaFX Application Thread] INFO : Shutting down
19:19:02.951 [JavaFX Application Thread] TRACE: Saving configuration
19:19:02.963 [JavaFX Application Thread] TRACE: Shutting down thread executors
```
Can't reproduce.

**Comment by LovesAsuna** [comment]
win10 professional edition and openjdk11

**Comment by Col-E** [comment]
Maybe the cache folder jars are malformed? Can try deleting this folder and retarting

`%APPDATA%\Recaf\dependencies`

**Comment by LovesAsuna** [comment]
I found that I can run on openjdk15.Then  I gave up using openjdk11
