### ISSUE TITLE
Exception at com.apple.laf.AquaMenuPainter.paintMenuBarBackground(AquaMenuPainter.java:145)

### ISSUE THREAD

**Issue by CaledoniaProject** [Col-E/Recaf#36]
I'm using recaf to edit `target/recaf-0.9-jar-with-dependencies.jar` itself, it sometimes raises exception like this ... although the application did not crash, but you might wanna look at it

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.apple.laf.AquaMenuPainter.paintMenuBarBackground(AquaMenuPainter.java:145)
	at com.apple.laf.AquaMenuBarUI.paint(AquaMenuBarUI.java:74)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
```

**Comment by CaledoniaProject** [comment]
The exception is thrown on startup, re-producable with master branch.

**Comment by Col-E** [comment]
Looks like it's an osx LAF issue in combination with how I handle applying themes. According to https://lists.apple.com/archives/java-dev/2010/Mar/msg00181.html

> You are using the Aqua Look and Feel's ScreenMenuBar, without having Aqua actually installed: this is not supported.

I _think_ the solution would be calling UIManager's `install(lafName, lafClass)` with the `com/apple/laf/AquaLookAndFeel` class for osx users. Hopefully a small plugin can fix this.

**Comment by Col-E** [comment]
I pushed a commit to `master` which shifts the order of displaying the UI to after plugins load. Can you plop this plugin _(jar inside the zip)_ into your `<recaf>/plugins` folder? 

Plugin contents:
```java
public class OsxThemeFix implements Plugin {
   @Override
   public void init() {
      SwingUtilities.invokeLater(new Runnable() {            
         @Override
         public void run() {
            UIManager.installLookAndFeel("Aqua", "com.apple.laf.AquaLookAndFeel");
         }
      });
   }
}
```

[OsxThemeFix.zip](https://github.com/Col-E/Recaf/files/1683810/OsxThemeFix.zip)

**Comment by CaledoniaProject** [comment]
The error stays the same

```
%> ls plugins/
./  ../  OsxThemeFix.jar
%> mvn clean package
...
%> java -jar target/recaf-0.9-jar-with-dependencies.jar
[INFO:2/1/18 11:21 AM] Setting up Recaf
[INFO:2/1/18 11:21 AM]    Loading config
[INFO:2/1/18 11:21 AM]       Loading config: ASM
[INFO:2/1/18 11:21 AM]       Loading config: Theme
[INFO:2/1/18 11:21 AM]       Loading config: UserInterface
[window.method.opcode.edit, window.method.opcode.new.before, window.method.opcode.new.after, window.method.opcode.move.up, window.method.opcode.move.down, window.method.opcode.gotodef, window.method.opcode.gotojump, window.method.opcode.saveblock, window.method.opcode.insertblock, window.method.opcode.remove]
[window.member.decompile, window.member.vars, window.member.editopcodes, window.member.catch, window.member.verify, window.member.define, window.member.search, window.member.add, window.member.remove]
[INFO:2/1/18 11:21 AM]       Loading config: CodeBlocks
[INFO:2/1/18 11:21 AM]       Loading config: Agent
[FINE:2/1/18 11:21 AM]    Loading language from: /resources/lang/en.json
[INFO:2/1/18 11:21 AM]    Loading attach api
[INFO:2/1/18 11:21 AM]    Creating UI
[INFO:2/1/18 11:21 AM]    Loading plugins
[INFO:2/1/18 11:21 AM]    Displaying UI
[INFO:2/1/18 11:21 AM] Finished setup
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.apple.laf.AquaMenuPainter.paintMenuBarBackground(AquaMenuPainter.java:145)
	at com.apple.laf.AquaMenuBarUI.paint(AquaMenuBarUI.java:74)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
        ...
```

**Comment by Col-E** [comment]
Ok then it looks like I have to re-evaluate how theme's are applied. The plugin probably doesn't work because there's still a delay in setting the theme _(which was put in place due to a non-delayed execution resulting in incomplete theme-application)_. I can't easily test this alone since I don't have any apple computers.

**Comment by CaledoniaProject** [comment]
No problem, it's not a fatal error anyway. Perhaps this would help https://stackoverflow.com/questions/23201030/what-is-a-look-and-feel-that-is-compatible-with-mac

**Comment by Col-E** [comment]
If you put `UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());` at the beginning on `main` does the exception get raised?

**Comment by CaledoniaProject** [comment]
In main()

```
	public static void main(String[] args) {
		try {
			System.out.println("before setLookAndFeel");
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
			System.out.println("after setLookAndFeel");
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		LaunchParams params = new LaunchParams();
		start(args, params);
	}
```

Output

```
%> java -jar target/recaf-0.9-jar-with-dependencies.jar
before setLookAndFeel
after setLookAndFeel
[INFO:2/1/18 2:54 PM] Setting up Recaf
[INFO:2/1/18 2:54 PM]    Loading config
```

**Comment by Col-E** [comment]
Does that mean adding the system LAF to main resolves the exception?

**Comment by CaledoniaProject** [comment]
Yes

```
	public static void main(String[] args) {
		try {
			UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
		} catch (Exception e) {
			e.printStackTrace();
		}
		LaunchParams params = new LaunchParams();
		start(args, params);
	}
```

**Comment by Col-E** [comment]
OK I'll work it into a commit later today.

**Comment by CaledoniaProject** [comment]
It works by now but I found another bug. There are three "Java Programs" in the file dialog ...

![screenshot 2018-02-02 at 14 47 05](https://user-images.githubusercontent.com/1357701/35720301-00b792fa-0828-11e8-97b8-938c4545f763.jpg)

**Comment by Col-E** [comment]
![image](https://user-images.githubusercontent.com/21371686/35722402-2a5ab40c-07c4-11e8-9cdc-41790b1b0822.png)

Should be put under an issue of it's own but it looks fine on my end.

**Comment by CaledoniaProject** [comment]
Looks like a compiler cache issue, the problem is now gone ...
