### ISSUE TITLE
[ParrotOS] Wrong decompilaton causes runtime errors while modifying something

### ISSUE THREAD

**Issue by CYB3RMX** [Col-E/Recaf#362]
I installed latest release of the program and begin to edit my apps variable names etc. While program decompile the jar file with any decompiler it converts some variable types to wrong types like ```int -> ınt```. So program throws errors like this:
```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: Unknown primitive type field 'ınt'
	at me.coley.recaf.util.JavaParserUtil.primTypeToDesc(JavaParserUtil.java:674)
	at me.coley.recaf.util.JavaParserUtil.primTypeToDesc(JavaParserUtil.java:635)
	at me.coley.recaf.util.JavaParserUtil.getDescriptor(JavaParserUtil.java:457)
	at me.coley.recaf.util.JavaParserUtil.getDescriptor(JavaParserUtil.java:416)
	at me.coley.recaf.util.JavaParserUtil.getDescriptor(JavaParserUtil.java:338)
	at me.coley.recaf.util.JavaParserUtil.checkForDeclaredSelection(JavaParserUtil.java:200)
	at me.coley.recaf.util.JavaParserUtil.getSelection(JavaParserUtil.java:133)
	at me.coley.recaf.ui.controls.text.JavaContextHandling.getSelection(JavaContextHandling.java:51)
	at me.coley.recaf.ui.controls.text.ContextHandling.lambda$new$0(ContextHandling.java:50)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
Is there any way or something to fix that? 
Thank you.

**Comment by Col-E** [comment]
Can you provide a more detailed explanation and so I can recreate this behavior? I can't really understand what happened from your issue description.

**Comment by CYB3RMX** [comment]
Sorry for my bad eng :)
So try to explain my issue step by step
1) I tried to open my jar file with program everything looks good
2) Program decompiles my file with Procyon decompiler
3) While I reading the decompiled code I see some of variables have incorrect letters
4) Then when I try select anything in the decompiled code program throws errors like what i said.
![issue](https://user-images.githubusercontent.com/42123683/111851414-f2232580-890a-11eb-8402-83979f0b347b.jpg)

**Comment by DJtheRedstoner** [comment]
I believe this is a common issue with the Turkish locale in java, is your computer by any chance set to Turkish?

**Comment by CYB3RMX** [comment]
@DJtheRedstoner I set my system locale to english and error fixed :D
Thank you so much :)

**Comment by Col-E** [comment]
Adding a fix for this in the next release by changing the default Locale. Since we don't really use the locale system anyways it shouldn't be an issue to change it so this doesn't occur.
