### ISSUE TITLE
Error while renaming fields, methods, and classes with specific obfuscation

### ISSUE THREAD

**Issue by c01dc0ffee** [Col-E/Recaf#380]
I want to use this opportunity to thank you for developing this program. I've been using Recaf for years and watching it grow every update has been incredible.

**Describe the bug**

I'm unable to rename fields, methods, or classes in a particular jar I'm analyzing. The rename dialog opens and I'm able to change the name, but the program fails while trying to rename the element. This bug has only occurred on this obfuscated jar, but I'm not sure that it is an intentional feature of the obfuscator. 

According to stdout, phantom analysis fails with a stack trace I've given below, which may be related. Phantom analysis does not fail with other jars that I've tested that are able to rename elements correctly.

Additionally, there are a handful of classes which are unable to be parsed with the ASM reader when the jar file is loaded. I'm not sure if this is related, as I recall it happening in other samples, but I am not sure if this affects the ability to rename elements in those cases. The following log message is the only information I have on this. Maybe there is some verbose launch option for Recaf that will enable me to provide more detailed information here. Please let me know if this is the case and I will share that here.
```
15:18:37.714 [ForkJoinPool-1-worker-3] WARN : Invalid class "main/qrz.class" - Cannot be parsed with ASM reader
Adding as a file instead.
```

**To Reproduce**

1. Open obfuscated jar (I'm unable to provide a sample)
2. Navigate to any class field
3. Attempt to rename the field to a similar, qualified name
4. Renaming dialog modal disappears, the field is not renamed
5. A stack trace is printed to stdout

**Exception**

```
Exception in thread "JavaFX Application Thread" java.lang.NegativeArraySizeException: -1
        at org.objectweb.asm.Frame.merge(Frame.java:1222)
        at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
        at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
        at org.objectweb.asm.MethodVisitor.visitMaxs(MethodVisitor.java:773)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2642)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:721)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at me.coley.recaf.mapping.Mappings.accept(Mappings.java:210)
        at me.coley.recaf.mapping.Mappings.accept(Mappings.java:186)
        at me.coley.recaf.mapping.Mappings.accept(Mappings.java:157)
        at me.coley.recaf.ui.controls.RenamingTextField.defaultAction(RenamingTextField.java:293)
        at me.coley.recaf.ui.controls.RenamingTextField.lambda$new$3(RenamingTextField.java:58)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8879)
        at com.sun.javafx.scene.control.behavior.TextFieldBehavior.fire(TextFieldBehavior.java:184)
        at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(TextInputControlBehavior.java:330)
        at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.stage.PopupWindow$PopupEventRedirector.handleKeyEvent(PopupWindow.java:1001)
        at javafx.stage.PopupWindow$PopupEventRedirector.handleRedirectedEvent(PopupWindow.java:973)
        at com.sun.javafx.event.EventRedirector.dispatchCapturingEvent(EventRedirector.java:106)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
        at com.sun.javafx.event.EventRedirector.redirectEvent(EventRedirector.java:124)
        at com.sun.javafx.event.EventRedirector.dispatchCapturingEvent(EventRedirector.java:103)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$KeyHandler.process(Scene.java:4058)
        at javafx.scene.Scene$KeyHandler.access$1500(Scene.java:4004)
        at javafx.scene.Scene.processKeyEvent(Scene.java:2121)
        at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2595)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
        at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
        at com.sun.glass.ui.View.notifyKey(View.java:971)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

The following is the stack trace provided when phantom analysis fails:
```
15:19:22.718 [ForkJoinPool-1-worker-7] ERROR: Failed to analyze phantom references for primary resource
java.lang.RuntimeException: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 74: Insufficient maximum stack size.
        at org.clyze.jphantom.JPhantom.run(JPhantom.java:76)
        at me.coley.recaf.workspace.PhantomResource.populatePhantoms(PhantomResource.java:120)
        at me.coley.recaf.workspace.Workspace.lambda$analyzePhantoms$2(Workspace.java:192)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 74: Insufficient maximum stack size.
        at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:296)
        at org.clyze.jphantom.constraints.extractors.TypeConstraintExtractor.visit(TypeConstraintExtractor.java:58)
        at org.clyze.jphantom.constraints.extractors.TypeConstraintExtractor.visit(TypeConstraintExtractor.java:46)
        at org.clyze.jphantom.JPhantom.run(JPhantom.java:74)
        ... 8 common frames omitted
Caused by: java.lang.IndexOutOfBoundsException: Insufficient maximum stack size.
        at org.objectweb.asm.tree.analysis.Frame.push(Frame.java:273)
        at org.objectweb.asm.tree.analysis.Frame.execute(Frame.java:326)
        at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:188)
        ... 11 common frames omitted
```

**Comment by codingsocks** [comment]
> Additionally, there are a handful of classes which are unable to be parsed with the ASM reader when the jar file is loaded. I'm not sure if this is related, as I recall it happening in other samples, but I am not sure if this affects the ability to rename elements in those cases.

ASM failing to parse a class file is usually really bad when it comes to obfuscated samples, we have the CAFED00D library to parse class files and fix stuff that breaks ASM because the ASM developers refuse to fix bugs in their library 🤷 

Anyway, 

> This bug has only occurred on this obfuscated jar, but I'm not sure that it is an intentional feature of the obfuscator.

It probably is meant to break Recaf or other ASM parsing tools directly, there's a few obfuscators that specifically target breaking ASM as to break decompilation / bytecode editing tools like Recaf. We'll need a sample to fix this, or a more detailed log.

**Comment by Col-E** [comment]
> I want to use this opportunity to thank you for developing this program. I've been using Recaf for years and watching it grow every update has been incredible.

Aww thanks :)

> Additionally, there are a handful of classes which are unable to be parsed with the ASM reader when the jar file is loaded. I'm not sure if this is related, as I recall it happening in other samples, but I am not sure if this affects the ability to rename elements in those cases.

Like Wolife said this part of the issues requires a sample to properly address. And yes, assuming the class isn't a red herring/junk then renaming things will not update the classes that are unrecognizable. 

> This bug has only occurred on this obfuscated jar, but I'm not sure that it is an intentional feature of the obfuscator.

In specific case of renaming not working with the given stack-trace, I understand what's happening here but I'm not yet sure how to _properly_ address things. 

The exception occurs here: `accept(updated, cr, ClassReader.SKIP_FRAMES, ClassWriter.COMPUTE_FRAMES);`

```
Exception in thread "JavaFX Application Thread" java.lang.NegativeArraySizeException: -1
        at org.objectweb.asm.Frame.merge(Frame.java:1222)
        at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
        at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
        at org.objectweb.asm.MethodVisitor.visitMaxs(MethodVisitor.java:773)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2642)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:721)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at me.coley.recaf.mapping.Mappings.accept(Mappings.java:210)
        at me.coley.recaf.mapping.Mappings.accept(Mappings.java:186)
        at me.coley.recaf.mapping.Mappings.accept(Mappings.java:157)
```

You'll need frames to execute code, so we discard existing ones, rename the classes, then generate new ones. I believe you can't get away with not using `COMPUTE_FRAMES` in this case. Now if ASM can't figure out the stack-frame logic for a method it'll just die like it does here. Without a sample I can't say much else, but some here are some possibilities:

 - The method exists solely to supply code that can't be validated by ASM and isn't necessary for normal program operation.
 - The method is obfuscated in such a way where ASM cannot figure out how to generate proper stack-frames.

-------

The phantom analysis failing to generate isn't the end of the world, but it does prevent some very convenient Recaf functionality. The `Caused by: java.lang.IndexOutOfBoundsException: Insufficient maximum stack size.` can be bypasses if we hackily just set the max-stack size to some arbitrary large number. Cause can have similar reasons as the above.

**Comment by c01dc0ffee** [comment]
Okay, with the help of your comments, I think I've figured this out.

> It probably is meant to break Recaf or other ASM parsing tools directly

Ironically, this was actually being caused by the deobfuscator I was using before Recaf ([java-deobfuscator](https://github.com/java-deobfuscator/deobfuscator/)). The deobfuscator doesn't automatically resolve dependencies, so it won't be able to recompute stack frames. The error message in the program is like this:
```
Error: java/lang/Object could not be found while writing main/oq. Using COMPUTE_MAXS
```

I'm not familiar with the JVM but your comment about COMPUTE_FRAMES helped me figure out [where to look](https://stackoverflow.com/questions/29332094/asm-5-when-initializing-a-classwriter-what-is-the-difference-between-compute-m). 

The deobfuscator program doesn't recompute stack frames without all the dependency jars present (presumably this is where the `-1` value comes from in `java.lang.NegativeArraySizeException`.) When the deobfuscated jar is loaded in Recaf, this probably causes phantom analysis to fail (`Insufficient maximum stack size`.) I'm not sure, but I think this also causes ASM to fail to read some of the classes. `main/qrz.class` mentioned above can be parsed before deobfuscation, but most classes are able to be parsed without stack frames computed, so something else might be going on. Maybe even COMPUTE_MAXS fails in these cases. 

Anyway, I'm confident invalid stack frame computation post-obfuscation is to blame here. Pre-computed stack frames are required for code execution, so it's sensible that Recaf requires them. Maybe Recaf can catch invalid stack frames and display a warning to the user, or otherwise prioritize `ClassWriter.COMPUTE_FRAMES` but skip computing frames as a fall back and warn the user about the pitfall, for robustness.

Thank you both for your help in figuring this out!

**Comment by Col-E** [comment]
Great to hear this got resolved 👍
