### ISSUE TITLE
Strange error upon attaching (maybe javafx)

### ISSUE THREAD

**Issue by xrnss** [Col-E/Recaf#400]
i'm attaching to lunar client (removed jvm args of disable attach) and this is happening and im not really sure. i think its this bit: `java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.getResource(String)" because "<local2>" is null`

```
[2021-08-16 09:15:56.064] [info]  [OUTPUT] 09:15:56.059 [Attach Listener] WARN : Failed to delete old log file, will append instead
09:15:56.062 [Attach Listener] INFO : Recaf-2.20.1
09:15:56.063 [Attach Listener] INFO : Starting as agent...

[2021-08-16 09:15:56.296] [info]  [OUTPUT] 09:15:56.295 [Attach Listener] TRACE: Loading configuration

[2021-08-16 09:15:59.481] [info]  [OUTPUT] 09:15:59.480 [Attach Listener] INFO : Loaded instrumentation workspace

[2021-08-16 09:15:59.496] [info]  [OUTPUT] 09:15:59.489 [Attach Listener] INFO : Loaded 1 plugins

[2021-08-16 09:16:01.873] [info]  [OUTPUT] Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.getResource(String)" because "<local2>" is null

[2021-08-16 09:16:01.884] [info]  [OUTPUT] 	at me.coley.recaf.ui.MainWindow.lambda$get$2(MainWindow.java:205)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.getResource(String)" because "<local2>" is null
	at javafx.graphics/com.sun.javafx.css.StyleManager.getURL(Unknown Source)
	at javafx.graphics/com.sun.javafx.css.StyleManager.loadStylesheetUnPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.css.StyleManager.loadStylesheet(Unknown Source)
	at javafx.graphics/com.sun.javafx.css.StyleManager.processStylesheets(Unknown Source)
	at javafx.graphics/com.sun.javafx.css.StyleManager.gatherSceneStylesheets(Unknown Source)
	at javafx.graphics/com.sun.javafx.css.StyleManager.findMatchingStyles(Unknown Source)
	at javafx.graphics/javafx.scene.CssStyleHelper.createStyleHelper(Unknown Source)
	at javafx.graphics/javafx.scene.Node.reapplyCss(Unknown Source)
	at javafx.graphics/javafx.scene.Node.doProcessCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Node$1.doProcessCSS(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSSImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.superProcessCSSImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.superProcessCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Node.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(Unknown Source)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Unknown Source)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(Unknown Source)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(Unknown Source)
	at javafx.graphics/javafx.stage.Window.setShowing(Unknown Source)
	at javafx.graphics/javafx.stage.Window.show(Unknown Source)
	at javafx.graphics/javafx.stage.Stage.show(Unknown Source)
	at me.coley.recaf.ui.MainWindow.start(MainWindow.java:63)
	at me.coley.recaf.ui.MainWindow.lambda$get$2(MainWindow.java:203)
	... 7 more

[2021-08-16 09:16:02.251] [info]  [OUTPUT] Exception in thread "JavaFX Application Thread" 
[2021-08-16 09:16:02.260] [info]  [OUTPUT] java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.getResource(String)" because "<local2>" is null
	at javafx.graphics/com.sun.javafx.css.StyleManager.getURL(Unknown Source)
	at javafx.graphics/com.sun.javafx.css.StyleManager.loadStylesheetUnPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.css.StyleManager.loadStylesheet(Unknown Source)
	at javafx.graphics/com.sun.javafx.css.StyleManager.processStylesheets(Unknown Source)
	at javafx.graphics/com.sun.javafx.css.StyleManager.gatherSceneStylesheets(Unknown Source)
	at javafx.graphics/com.sun.javafx.css.StyleManager.findMatchingStyles(Unknown Source)
	at javafx.graphics/javafx.scene.CssStyleHelper.createStyleHelper(Unknown Source)
	at javafx.graphics/javafx.scene.Node.reapplyCss(Unknown Source)
	at javafx.graphics/javafx.scene.Node.doProcessCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Node$1.doProcessCSS(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSSImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.superProcessCSSImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.superProcessCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(Unknown Source)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Node.processCSS(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by xrnss** [comment]
#399 this leads from here

**Comment by Col-E** [comment]
Looks like its a known bug in JavaFX, says so in the source code.

![image](https://user-images.githubusercontent.com/21371686/130339278-8abffbc1-f2e3-46dc-8689-aa1c3ca2bdf5.png)

**Comment by Col-E** [comment]
![image](https://user-images.githubusercontent.com/21371686/130339934-09dbc2f6-5aca-401f-ba9b-7fd00d35e385.png)

It was also crashing because it tried to rename the extension to `bss` as you can see in the prior screenshot. I didn't look at much of the internals of why it does this, but thankfully there's a system property to disable this.

Then you can just set the thread's context classloader and it works. 

Will push up a fix shortly.

**Comment by Col-E** [comment]
![image](https://user-images.githubusercontent.com/21371686/130340052-229cc0d4-cf2d-47a3-9855-9e0d34f0f0de.png)

Works :)

**Comment by xrnss** [comment]
thank you so much for your time <3
