### ISSUE TITLE
Repackage bug when edit springboot package

### ISSUE THREAD

**Issue by iflody** [Col-E/Recaf#401]
**Describe the bug**

> 1. Spring boot will check if the nested jar is compressed, so if use recaf to edit the springboot application jar directly and export it, it will occurs: Spring boot :unable to open nested entry 'WEB-INF/lib-provided/ecj-3.12.3.jar'
> 2. Recaf export jar will export the original package to the root of the jar, if the package is the org/spring/boot/loader it works fine, but if the original package is in the BOOT-INF/classes/, the conflict occurs, due to the jvm SPI, the class will be find in the jvm native class loader(because the native class loader will find it in the classpath at first, and will not delegate to the LaunchedURLClassLoader),and the spring boot application's classloader will be the ClassLoaders$AppClassLoader, when the main class try to load the other spring class, it will failed with NoClassDefFoundError because the AppClassLoader's ucp doesn't contains the BOOT-INF/lib, it is included in the LaunchedURLClassLoader. So when write the class back to the new jar, it should use the original path.

**To Reproduce**

1. Download https://transfer.sh/VUk1Pk/app.jar
2. extract app.jar
3. Use recaf to open the app.jar
4. Add app/BOOT-INF/lib to library
5. do some edit in code/shellsniper
6. export jar to app_patched.jar
7. run the app_patched.jar
8. You will find the first bug occurs, I patched it and then the second bug occurs.

**Exception**

The first bug:

```
java.lang.IllegalStateException: Failed to get nested archive for entry
```

The second bug:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
	at code.shellsniper.Application.main(Application.java:9)
	... 8 more
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 9 more
```

My patch to the first bug: https://transfer.sh/OIv5Ij/export.patch

I don't make a pr because I think the compress option should be a user-defined option, and I'm not familar with recaf, so I have not figure out how to solve it.
And for the second bug, I find that when the classes added to the map,the original class info has lost, so this may be a big change in the code.

**Comment by Col-E** [comment]
Yeah, the compression patch would be relatively simple to adjust to configurable. But at the moment the way workspaces are laid out in `2.x` doesn't make managing non-standard class locations like this easy to track. For instance, if you rename a class that information still needs to be tracked. The way that `.war` is supported assumes things are all in the special directory anyways, which we can't really do for the `.jar` resources...

The `3.x` branch's workspace layout would make supporting this pretty do-able though. All items are wrapped in a data type rather than being stored raw as `byte[]`. Some directory information could be attached to these entries.

**Comment by Col-E** [comment]
So I added your compression patch: https://github.com/Col-E/Recaf/commit/c6248bea277745a0cfaca544fd6bb12f708507e8

You can enable it by manually editing the `backend.json` in the Recaf directory _(I didn't add it to the UI because I'm not sure where to put it at the moment. Sorry)_.

**Comment by Col-E** [comment]
I'm going to close this now since there is a solution. It may not be ideal but current plan is putting my time into the 3X project which has a better means of addressing it. The config system is more diverse so it is a toggle-able feature in the UI on there. Aside from major bug fixes I do not plan on adding any new significant features to the current 2X releases. As always I'm always available for feedback and questions.
