### ISSUE TITLE
Unable to parse the class

### ISSUE THREAD

**Issue by MizzMaster** [Col-E/Recaf#430]
**Describe the bug**

I was working on a deobfuscated jar file, It was originally obfuscated by Radon and then deobfuscated by java-deobfuscator. I found a class that ASM *probably* couldn't parse it so it was showing as a *file* rather than a *class*. After I passed the jar through the Threadtear, the class became visible as a normal *class* in Recaf

**To Reproduce**

1. Open the [class that has NOT passed through Threadtear](https://workupload.com/file/VUn2NWj5gGN) in Recaf (and see it shows as a *file*)
2. Open the [class that has passed through Threadtear](https://workupload.com/file/CWw9d5W4TTw) in Recaf (and see it shows as a *class*)

(Even if the other ones in the jar are deobfuscated successfully, this class remains obfuscated , *probably* java-deobfuscator couldn't parse it, too)

I don't know what the cause is, but i guess it is because ASM-crashing junk data. I know that kinda stuff should be handled by the deobfuscators not Recaf, but like a bug I found earlier (junk data causing renaming to fail), it is better to make it handle, in my opinion.

**Comment by win32kbase** [comment]
Seems to be a JPhantom problem.

```
java.lang.RuntimeException: org.objectweb.asm.tree.analysis.AnalyzerException: Execution can fall off the end of the code
	at org.clyze.jphantom.JPhantom.run(JPhantom.java:86)
	at me.coley.recaf.util.JPhantomUtil.generate(JPhantomUtil.java:76)
	at me.coley.recaf.util.CompileDependencyUpdater.createPhantoms(CompileDependencyUpdater.java:108)
	at me.coley.recaf.util.CompileDependencyUpdater.lambda$null$0(CompileDependencyUpdater.java:74)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: org.objectweb.asm.tree.analysis.AnalyzerException: Execution can fall off the end of the code
	at org.objectweb.asm.tree.analysis.Analyzer.findSubroutine(Analyzer.java:391)
	at org.objectweb.asm.tree.analysis.Analyzer.analyze(Analyzer.java:139)
	at org.clyze.jphantom.constraints.extractors.TypeConstraintExtractor.visit(TypeConstraintExtractor.java:58)
	at org.clyze.jphantom.constraints.extractors.TypeConstraintExtractor.visit(TypeConstraintExtractor.java:46)
	at org.clyze.jphantom.JPhantom.run(JPhantom.java:84)
	... 8 more
```

**Comment by Col-E** [comment]
> Seems to be a JPhantom problem.

This is only for the _"patched"_ file though. The main concern is that it doesn't show up as a class unpatched, which should be handled by CAFED00D. I'll take a look at it some time tomorrow.

**Comment by win32kbase** [comment]
> > Seems to be a JPhantom problem.
> 
> This is only for the _"patched"_ file though. The main concern is that it doesn't show up as a class unpatched, which should be handled by CAFED00D. I'll take a look at it some time tomorrow.

Oops, you are right

**Comment by xcfrg** [comment]
Can no longer reproduce the original issue on at least 427b048c07b7a5791514295e54484f6a17b0ffbc of dev3:
`17:31:56.237 [ClassPatchingListener:INFO] Recovered 1/1 (100.00%) malformed classes`
There are still some issues with the fields & methods outline
![Screenshot_20220419_173349](https://user-images.githubusercontent.com/30675315/164105620-59f8b846-432b-4754-b30a-d6d599c925a8.png)
(screenshot from the fallback decompiler as cfr completely fails on this class)

**Comment by xxDark** [comment]
Whats the issue with field/method outline? I can't see it?

**Comment by Col-E** [comment]
@xxDark It doesn't show synthetics by default. I think we should probably make it invert that so synthetics _are_ the default.

**Comment by xxDark** [comment]
@MizzMaster Is this class even accepted by JVM's verifier? The IFEQ instruction jumps outside of code.
![code](https://user-images.githubusercontent.com/19853368/164116874-b5750339-159a-4b74-a6b0-d5e8bba988a4.png)
