### ISSUE TITLE
Failed to load classes from resource java.util.zip.ZipException: invalid code lengths set

### ISSUE THREAD

**Issue by pp0236** [Col-E/Recaf#431]
**Describe the bug**

> jar did;t loaded in workspace

**To Reproduce**

1. Open sample 'modid.jar' ([sample.zip](https://github.com/Col-E/Recaf/files/7650252/sample.zip))
2. error in console

**Exception**

If applicable, add the exception/stacktrace.
```
21:16:53.670 [ForkJoinPool-1-worker-7] ERROR: Failed to load classes from resource "modid-1.0.jar"
java.util.zip.ZipException: invalid code lengths set
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:165)
        at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:197)
        at java.base/java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:143)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:121)
        at me.coley.recaf.workspace.JarResource.loadClasses(JarResource.java:39)
        at me.coley.recaf.workspace.JavaResource.getClasses(JavaResource.java:230)
        at me.coley.recaf.command.impl.LoadWorkspace.call(LoadWorkspace.java:109)
        at me.coley.recaf.control.gui.GuiController$1.call(GuiController.java:116)
        at me.coley.recaf.control.gui.GuiController$1.call(GuiController.java:101)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
21:16:53.783 [ForkJoinPool-1-worker-7] ERROR: Failed to load files from resource "modid-1.0.jar"
java.util.zip.ZipException: invalid code lengths set
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:165)
        at me.coley.recaf.util.IOUtil.transfer(IOUtil.java:45)
        at me.coley.recaf.util.IOUtil.toByteArray(IOUtil.java:261)
        at me.coley.recaf.util.IOUtil.toByteArray(IOUtil.java:292)
        at me.coley.recaf.workspace.JarResource.loadFiles(JarResource.java:77)
        at me.coley.recaf.workspace.JavaResource.getFiles(JavaResource.java:264)
        at me.coley.recaf.command.impl.LoadWorkspace.call(LoadWorkspace.java:110)
        at me.coley.recaf.control.gui.GuiController$1.call(GuiController.java:116)
        at me.coley.recaf.control.gui.GuiController$1.call(GuiController.java:101)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by Col-E** [comment]
Fixed in the development 3x branch, if somebody wants to backport the logic is here: https://github.com/Col-E/Recaf/blob/dev3/recaf-core/src/main/java/me/coley/recaf/workspace/resource/source/ArchiveFileContentSource.java
