### ISSUE TITLE
IOException: Detached from target VM

### ISSUE THREAD

**Issue by u9g** [Col-E/Recaf#439]
**Describe the bug**

Tried to attach to a vm

Can't give a sample here, ping me on discord

**Exception**

If applicable, add the exception/stacktrace.
```
java.io.IOException: Detached from target VM
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.execute(VirtualMachineImpl.java:101)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:94)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:119)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:147)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:538)
	at me.coley.recaf.ui.controls.pane.AttachPane$VMInfo.lambda$attach$5(AttachPane.java:417)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1414)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Screenshots**
https://i.imgur.com/dfjkZfJ.png

**Comment by Col-E** [comment]
This is the sort of issue which can be entirely circumstancial to the sample. 

Usually the case is a target application has bundled a JVM but encorperates some measures to prevent debugging/dumping. 

If you can provide a sample that you can share we'll be able to look into this.
