### ISSUE TITLE
NoClassDefFoundError: javafx/event/EventTarget

### ISSUE THREAD

**Issue by randomshitter** [Col-E/Recaf#452]
Getting an error when attempting to run the jar.

`java -jar recaf-2.21.11-J8-jar-with-dependencies.jar`

Full stacktrace:

> Exception in thread "main" java.lang.NoClassDefFoundError: javafx/event/EventTarget
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at me.coley.recaf.command.impl.Initializer.run(Initializer.java:60)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at me.coley.recaf.Recaf.launch(Recaf.java:103)
	at me.coley.recaf.Recaf.main(Recaf.java:52)
Caused by: java.lang.ClassNotFoundException: javafx.event.EventTarget
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 19 more

Happens when building it myself too.

![image](https://user-images.githubusercontent.com/95352120/150229265-96228e82-0ea0-4668-a086-941d59397376.png)

![image](https://user-images.githubusercontent.com/95352120/150230160-658d78d9-193d-49fe-806a-3f27e6d9dc63.png)

**Comment by win32kbase** [comment]
![image](https://user-images.githubusercontent.com/6201484/150232303-ea42d165-9b3d-48f2-9bea-e7336cfcd303.png)
Tested with identical JDK, worked fine

**Comment by Col-E** [comment]
![image](https://user-images.githubusercontent.com/21371686/150275830-736b75c4-eeca-41a7-9410-67d4a737c08b.png)

**Comment by Col-E** [comment]
If anyone can add details on how to make this reproducible feel free to comment / open the issue again.

**Comment by randomshitter** [comment]
> If anyone can add details on how to make this reproducible feel free to comment / open the issue again.

I'm not sure I can provide any details other than simply downloading the jar and attempting to run it. Happened on a clean wsl distro as well (though it was a different class which was not found).

Either way I've been able to run it by specifying the path to jfx:

`java --module-path <path-to-fx> --add-modules javafx.base -jar recaf-2.21.11-J8-jar-with-dependencies.jar`

**Comment by Col-E** [comment]
That's odd, because we have some logic that breaks down the module requirements so that shouldn't be necessary. Its hacky but its our approach to retaining both 8 and 11 support simultaneously at the moment.

**Comment by w1redch4d** [comment]
the problem occurs with openjdk 17.0.6 microsoft version in windows , here is the link to download : https://learn.microsoft.com/en-us/java/openjdk/download
