### ISSUE TITLE
Cannot run: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by CaveNightingale** [Col-E/Recaf#527]
**Describe the bug**
Can not run.
> A clear and concise description of what the bug is.

**To Reproduce**
 1，Run java -jar recaf-2.21.13-J8-jar-with-dependencies.jar（tested on Java 11 and Java 17）
 2, See error
**Exception**

If applicable, add the exception/stacktrace.
```
08:50:23.976 [main] INFO : Recaf-2.21.13
08:50:23.981 [main] INFO : - Java: 11.0.6 (OpenJDK 64-Bit Server VM)
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task
	at me.coley.recaf.command.impl.Initializer.run(Initializer.java:60)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at me.coley.recaf.Recaf.launch(Recaf.java:103)
	at me.coley.recaf.Recaf.main(Recaf.java:52)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 11 more
```

**Screenshots**
![IMG_20220424_164452.jpg](https://user-images.githubusercontent.com/51874645/164968257-a1aa0e39-e580-4875-bf50-186b44942d24.jpg)

**Comment by xxDark** [comment]
Delete JavaFX cache in Recaf's folder (the directory is located in AppData/Roaming on Windows) and try again

**Comment by CaveNightingale** [comment]
> Delete JavaFX cache in Recaf's folder (the directory is located in AppData/Roaming on Windows) and try again

Thanks. It works.
