### ISSUE TITLE
JPhantom exception in console

### ISSUE THREAD

**Issue by ghost** [Col-E/Recaf#530]
**Describe the bug**

> Happened after decompiling a jar file

**To Reproduce**

/

**Exception**

```
java.lang.StackOverflowError: null
        at java.base/java.util.Arrays$ArrayList.contains(Arrays.java:4378)
        at org.clyze.jphantom.adapters.AnnotationAdapter.visit(AnnotationAdapter.java:23)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at org.clyze.jphantom.adapters.InterfaceTransformer.visit(InterfaceTransformer.java:22)
        at org.clyze.jphantom.adapters.AnnotationAdapter.visit(AnnotationAdapter.java:29)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at org.clyze.jphantom.adapters.InterfaceTransformer.visit(InterfaceTransformer.java:22)
        at org.clyze.jphantom.adapters.AnnotationAdapter.visit(AnnotationAdapter.java:29)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at org.clyze.jphantom.adapters.InterfaceTransformer.visit(InterfaceTransformer.java:22)
        at org.clyze.jphantom.adapters.AnnotationAdapter.visit(AnnotationAdapter.java:29)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at org.clyze.jphantom.adapters.InterfaceTransformer.visit(InterfaceTransformer.java:22)
        at org.clyze.jphantom.adapters.AnnotationAdapter.visit(AnnotationAdapter.java:29)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at org.clyze.jphantom.adapters.InterfaceTransformer.visit(InterfaceTransformer.java:22)
        at org.clyze.jphantom.adapters.AnnotationAdapter.visit(AnnotationAdapter.java:29)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at org.clyze.jphantom.adapters.InterfaceTransformer.visit(InterfaceTransformer.java:22)
        at org.clyze.jphantom.adapters.AnnotationAdapter.visit(AnnotationAdapter.java:29)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        at org.clyze.jphantom.adapters.InterfaceTransformer.visit(InterfaceTransformer.java:22)
        at org.clyze.jphantom.adapters.AnnotationAdapter.visit(AnnotationAdapter.java:29)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:115)
        ...
```

**Comment by Col-E** [comment]
JPhantom is the tool that generates missing classes so recompiling works. You can disable it in the config menu. It is not required for using the assembler.
