### ISSUE TITLE
Unable to open DISPLAY

### ISSUE THREAD

**Issue by Mascantosh** [Col-E/Recaf#542]
**Describe the bug**

> Application doesn't startup

**To Reproduce**

1. java -jar recaf-2.21.13-J8-jar-with-dependencies.jar

**Exception**
```
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6442b0a6'
Exception in thread "main" java.lang.RuntimeException: Unable to initialize toolkit
	at me.coley.recaf.util.VMUtil.tkIint(VMUtil.java:186)
	at me.coley.recaf.ui.MainWindow.get(MainWindow.java:199)
	at me.coley.recaf.control.gui.GuiController.run(GuiController.java:44)
	at me.coley.recaf.command.impl.Initializer.startController(Initializer.java:73)
	at me.coley.recaf.Recaf.launch(Recaf.java:114)
	at me.coley.recaf.Recaf.main(Recaf.java:52)
Caused by: java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:181)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:179)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:291)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:293)
	at javafx.application.Platform.startup(Platform.java:113)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at me.coley.recaf.util.VMUtil.tkIint(VMUtil.java:182)
	... 5 more
```
**Versions**

**Java**
```
openjdk 18.0.1.1 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2, mixed mode)
```
**Sway**
```
sway version 1.7
```

**Comment by xxDark** [comment]
Check your GTK installation, this does not seem like Recaf issue to me

**Comment by RibozymeR** [comment]
JavaFX doesn't like being loaded as an unnamed module, so you have to include it in the module path, see also [this very nice answer](https://stackoverflow.com/a/53237667/10465255).
My solution was to run Recaf with
`java --module-path path/to/javafx/lib --add-modules javafx.controls -jar recaf-2.21.13-J8-jar-with-dependencies.jar`

**Comment by xxDark** [comment]
JavaFX runs fine in unnamed module in Recaf because we don't use Jigsaw module system
The answer on StackOverflow you provided resolved `IllegalAccessError`, not the issue mentioned here
If it in fact does solve it, I'll make an adjustment

**Comment by xxDark** [comment]
To clarify: provide the behaviour before and after the flag was added for Recaf

**Comment by RibozymeR** [comment]
JavaFX does not run fine as an unnamed modules for me; I need to add the module flags, without them I just now got the error
`Unsupported JavaFX configuration: classes were loaded from 'unnamed module @52cc8049'`
If this isn't intended behavior though, I can open a new issue about it.

**Comment by xxDark** [comment]
Thats just a warning, because we don't use module system at all and breaking "free" from it

**Comment by xxDark** [comment]
Closing, no response
