### ISSUE TITLE
can't run Recaf: class javafx.

### ISSUE THREAD

**Issue by PiprTuff** [Col-E/Recaf#551]
**Describe the bug**

Trying to run Recaf from cmd says no class named javafx.concurrent.Task found.

**To Reproduce**

1. Download the latest Recaf jar with all dependencies from Github releases.
2. cd into your downloaded jar's directory.
3. Run `java -jar recaf-bla-bla.jar`
**Exception**

If applicable, add the exception/stacktrace.
```
C:\Users\tawhi\Downloads>java -jar recaf-2.21.13-J8-jar-with-dependencies.jar
23:44:33.766 [main] INFO : Recaf-2.21.13
23:44:33.766 [main] INFO : - Java: 17.0.3 (OpenJDK Server VM)
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task
        at me.coley.recaf.command.impl.Initializer.run(Initializer.java:60)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at me.coley.recaf.Recaf.launch(Recaf.java:103)
        at me.coley.recaf.Recaf.main(Recaf.java:52)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 11 more
```

**Screenshots**

![Screenshot_5](https://user-images.githubusercontent.com/102426645/176002335-bfe5f2c8-ffce-486d-bde7-3957a887b305.png)

**Additional Information**
Java Version: 17.0.3 (Eclipse Adoptium, Downloaded from Official site)
OS: Windows 10 Pro

**Comment by xxDark** [comment]
Probably related https://github.com/Col-E/Recaf/issues/527
