### ISSUE TITLE
Recaf failed to run

### ISSUE THREAD

**Issue by Cloak3** [Col-E/Recaf#561]
**Console Output**

When using Java 11:
```
D:\Recaf>.\jdk-11.0.15+10\bin\java -jar recaf-2.21.13-J8-jar-with-dependencies.jar
14:14:34.710 [main] INFO : Recaf-2.21.13
14:14:34.712 [main] INFO : - Java: 11.0.15 (OpenJDK 64-Bit Server VM)
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task
        at me.coley.recaf.command.impl.Initializer.run(Initializer.java:60)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at me.coley.recaf.Recaf.launch(Recaf.java:103)
        at me.coley.recaf.Recaf.main(Recaf.java:52)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 11 more
```

When using Java 18:
```
D:\Recaf>java -jar recaf-2.21.13-J8-jar-with-dependencies.jar
14:09:56.535 [main] INFO : Recaf-2.21.13
14:09:56.537 [main] INFO : - Java: 18.0.1.1 (Java HotSpot(TM) 64-Bit Server VM)
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task
        at me.coley.recaf.command.impl.Initializer.run(Initializer.java:60)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at me.coley.recaf.Recaf.launch(Recaf.java:103)
        at me.coley.recaf.Recaf.main(Recaf.java:52)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 11 more
```

**Description**

Nothing happened when trying to run the application with a double-click.
Running with "java -jar" ended up showing the output above.
I'm currently using Windows 11 Home Edition x64.
Sorry, this issue might seem silly, for I'm so new to Java.

**Comment by Janmm14** [comment]
Install a JVM installation with an Azul Zulu JDK+FX installation.

**Comment by xxDark** [comment]
Delete javafx cache in AppData/Roaming/Recaf folder and try again.
