### ISSUE TITLE
Error fetching linux-arm32 JFX dependencies launching Recaf 2X

### ISSUE THREAD

**Issue by SprainedSpark89** [Col-E/Recaf#577]
**when i tried to use java 11 and java 17 it gave me an error**

> A clear and concise description of what the bug is.
error when using java 11
OS: Linux
Version: 11.0.16
Vendor: Raspbian

Exception: java.io.FileNotFoundException: https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+8/javafx-media-18-ea+8-linux-arm32.jar
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1920)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at me.coley.recaf.util.self.SelfDependencyPatcher.getLocalDependencies(SelfDependencyPatcher.java:76)
	at me.coley.recaf.util.self.SelfDependencyPatcher.ensureJavafxSupport(SelfDependencyPatcher.java:53)
	at me.coley.recaf.Recaf.init(Recaf.java:84)
	at me.coley.recaf.Recaf.main(Recaf.java:51)
error when using java 17
OS: Linux
Version: 17.0.3
Vendor: Eclipse Adoptium

Exception: java.io.FileNotFoundException: https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+8/javafx-media-18-ea+8-linux-arm32.jar
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at me.coley.recaf.util.self.SelfDependencyPatcher.getLocalDependencies(SelfDependencyPatcher.java:76)
	at me.coley.recaf.util.self.SelfDependencyPatcher.ensureJavafxSupport(SelfDependencyPatcher.java:53)
	at me.coley.recaf.Recaf.init(Recaf.java:84)
	at me.coley.recaf.Recaf.main(Recaf.java:51)
**To Reproduce**

1. use pi os 
**Exception**

i would think it would work because the os base of pi os is debian linux

**Comment by Col-E** [comment]
Looks like the suffix `-monocle` needs to be applied: https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+8/

You can download the jars manually to the `Recaf/dependencies` directory.

- https://repo1.maven.org/maven2/org/openjfx/javafx-base/18/javafx-base-18-linux-arm32-monocle.jar
- https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/18/javafx-graphics-18-linux-arm32-monocle.jar
- https://repo1.maven.org/maven2/org/openjfx/javafx-controls/18/javafx-controls-18-linux-arm32-monocle.jar
- https://repo1.maven.org/maven2/org/openjfx/javafx-media/18/javafx-media-18-linux-arm32-monocle.jar

**Comment by Col-E** [comment]
Closing as 4.X is the only branch we're working on going forward. How JFX is handled is now externalized to the launcher, or by the user if they wish to configure JFX themselves.
