### ISSUE TITLE
NPE when adding 2 dependent .class files

### ISSUE THREAD

**Issue by Amejonah1200** [Col-E/Recaf#582]
**NullPointerException**

**To Reproduce**

- Compile:
```java
public class Test {
    
    public int i = 0;
    public static final byte testb = 0;
    public static final short tests = 0;
    public static final int testi = 0;
    public static final long testl = 0;
    public static final float testf = 0;
    public static final double testd = 0;
    
    public static void main(String... args) {
      new Test().start();
    }
    
    public void start() {
      hi();
      System.out.println(i);
      i = 10;
      A a = new A().self();
      System.out.println(a.a);
      a.a = 10;
      System.out.println(a.a);
      System.out.println(a.hey(i)); 
      System.out.println("Hello World");
      Runnable test = this::hi;
    }
    
    public void hi() { }
    
    public class A {
      public int a = 0;
      
      public int hey(int i) { return a + i; }
      
      public A self() { return this; }
    }    
}
```
- Grab `Test.class` and `Test$A.class` into Recaf
- ↓

**Exception**

```
java.lang.NullPointerException: Cannot invoke "me.coley.recaf.graph.InheritanceGraph.getCommon(String, String)" because the return value of "me.coley.recaf.ui.util.Icons.getGraph()" is null
	at me.coley.recaf.ui.util.Icons.getClassIconProvider(Icons.java:325)
	at me.coley.recaf.ui.util.Icons.getClassIcon(Icons.java:347)
	at me.coley.recaf.ui.util.Icons.getResourceIcon(Icons.java:300)
	at me.coley.recaf.ui.control.ResourceSelectionList$ResourceCell.updateItem(ResourceSelectionList.java:113)
	at me.coley.recaf.ui.control.ResourceSelectionList$ResourceCell.updateItem(ResourceSelectionList.java:105)
	at javafx.scene.control.ListCell.updateItem(ListCell.java:485)
	at javafx.scene.control.ListCell.indexChanged(ListCell.java:337)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
	at javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1811)
	at javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1795)
	at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2970)
	at javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:2953)
	at javafx.scene.control.skin.VirtualFlow.recalculateAndImproveEstimatedSize(VirtualFlow.java:3025)
	at javafx.scene.control.skin.VirtualFlow.recalculateEstimatedSize(VirtualFlow.java:3017)
	at javafx.scene.control.skin.VirtualFlow$5.invalidated(VirtualFlow.java:860)
	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:904)
	at javafx.scene.control.skin.ListViewSkin.updateItemCount(ListViewSkin.java:343)
	at javafx.scene.control.skin.ListViewSkin.<init>(ListViewSkin.java:232)
	at javafx.scene.control.ListView.createDefaultSkin(ListView.java:989)
	at javafx.scene.control.Control.doProcessCSS(Control.java:899)
	at javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.scene.Node.processCSS(Node.java:9477)
	at javafx.scene.Scene.doCSSPass(Scene.java:572)
	at javafx.scene.Scene.preferredSize(Scene.java:1770)
	at javafx.scene.Scene$2.preferredSize(Scene.java:396)
	at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.stage.Window$12.invalidated(Window.java:1163)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.stage.Window.setShowing(Window.java:1239)
	at javafx.stage.Window.show(Window.java:1254)
	at javafx.stage.Stage.show(Stage.java:277)
	at javafx.stage.Stage.showAndWait(Stage.java:467)
	at javafx.scene.control.HeavyweightDialog.showAndWait(HeavyweightDialog.java:162)
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:346)
	at me.coley.recaf.ui.prompt.WorkspaceDropPrompts.createWorkspace(WorkspaceDropPrompts.java:56)
	at me.coley.recaf.ui.prompt.WorkspaceIOPrompts.lambda$handleFiles$0(WorkspaceIOPrompts.java:193)
	at me.coley.recaf.util.threading.ThreadUtil.lambda$wrap$1(ThreadUtil.java:187)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
```
(run on JDK 17 for helpful NPEs, JDK 11 gives this exception too)

**Comment by Col-E** [comment]
Seems like a race failure, doesn't happen for me but fixed via a null check
