### ISSUE TITLE
Opening non container files is not supported

### ISSUE THREAD

**Issue by Amejonah1200** [Col-E/Recaf#583]
**Exception**
```
java.io.IOException: Unhandled file type (header=publ/70-75-62-6c): java
    at me.coley.recaf.workspace.resource.DefaultContentSourceFactory.fromHeader(DefaultContentSourceFactory.java:99)
    at me.coley.recaf.workspace.resource.DefaultContentSourceFactory.create(DefaultContentSourceFactory.java:49)
    at me.coley.recaf.workspace.resource.ResourceIO.fromPath(ResourceIO.java:39)
    at me.coley.recaf.workspace.resource.ResourceIO.fromPath(ResourceIO.java:82)
    at me.coley.recaf.ui.prompt.WorkspaceDropPrompts.readResources(WorkspaceDropPrompts.java:142)
    at me.coley.recaf.ui.prompt.WorkspaceIOPrompts.handleFiles(WorkspaceIOPrompts.java:189)
    at me.coley.recaf.ui.prompt.WorkspaceIOPrompts.handleFiles(WorkspaceIOPrompts.java:175)
    at me.coley.recaf.ui.control.tree.WorkspaceTreeWrapper.lambda$onDragDrop$0(WorkspaceTreeWrapper.java:54)
    ...
```
is getting thrown upon opening an .java file.
![image](https://user-images.githubusercontent.com/50181314/182451436-7976635f-e352-460c-b1c4-c86efd1bd1fb.png)

This issue could also take other files (.json, .css, .yaml, .xml...) into scope as it can be useful when handling with multiple files, without the need to open an editor for that, if we have an editor at home.
Editor at home: Recaf

**Comment by Col-E** [comment]
Done in 99c129524a7192b929becdaa0d4b8073ab4fc106
