### ISSUE TITLE
ERROR: Failed to write remote dependency to cache

### ISSUE THREAD

**Issue by naseemr** [Col-E/Recaf#604]
**Describe the bug**

> A clear and concise description of what the bug is.
While running the command  java -jar recaf-2.21.13-J8-jar-with-dependencies.jar, I get the error " [main] ERROR: Failed to write remote dependency to cache"
**To Reproduce**
java -jar recaf-2.21.13-J8-jar-with-dependencies.jar
1. Open sample '...' _(provide sample download if possible)_
2. Navigate to '....'
3. Do something '....'

**Exception**

If applicable, add the exception/stacktrace.
```
stacktrace goes here
```

**Screenshots**

**Comment by Col-E** [comment]
From: https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/util/self/SelfDependencyPatcher.java#L83

There should be a stacktrace, but you did not provide any.

**Comment by naseemr** [comment]
Hi, thank you for your reply, where do I find the stacktrace?

**Comment by Amejonah1200** [comment]
> Hi, thank you for your reply, where do I find the stacktrace?

In the console, where you run the command in.

**Comment by Col-E** [comment]
Console as said before, but Recaf also creates log files. On windows `%APPDATA%/Recaf`

**Comment by naseemr** [comment]
Here is the console that pop up:
OS: Linux
Version: 18.0.2.1
Vendor: Oracle Corporation

Exception: java.net.ConnectException: Connection timed out
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:585)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:378)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at me.coley.recaf.util.self.SelfDependencyPatcher.getLocalDependencies(SelfDependencyPatcher.java:76)
	at me.coley.recaf.util.self.SelfDependencyPatcher.ensureJavafxSupport(SelfDependencyPatcher.java:53)
	at me.coley.recaf.Recaf.init(Recaf.java:84)
	at me.coley.recaf.Recaf.main(Recaf.java:51)

**Comment by Amejonah1200** [comment]
Well, do you have internet? It looks like you don't. You need to download them yourself.

**Comment by naseemr** [comment]
Unfortunately no internet. What do I need to download?

**Comment by Col-E** [comment]
Recaf 2.21.13 uses JavaFX `18-ea+8`. 

Grab the right jar for your system:

- https://repo1.maven.org/maven2/org/openjfx/javafx-base/18-ea+8/
- https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/18-ea+8/
- https://repo1.maven.org/maven2/org/openjfx/javafx-controls/18-ea+8/
- https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+8/

**Comment by Amejonah1200** [comment]
![image](https://user-images.githubusercontent.com/50181314/191606436-077b7876-8a48-4973-8ff5-9dd395847812.png)
![image](https://user-images.githubusercontent.com/50181314/191606491-2d339c28-b2c2-4de9-ba3d-431340e41f06.png)

For linux-aarch64:
  https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+8/javafx-media-18-ea+8-linux-aarch64.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-controls/18-ea+8/javafx-controls-18-ea+8-linux-aarch64.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/18-ea+8/javafx-graphics-18-ea+8-linux-aarch64.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-base/18-ea+8/javafx-base-18-ea+8-linux-aarch64.jar
For linux-arm32:
  https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+8/javafx-media-18-ea+8-linux-arm32.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-controls/18-ea+8/javafx-controls-18-ea+8-linux-arm32.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/18-ea+8/javafx-graphics-18-ea+8-linux-arm32.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-base/18-ea+8/javafx-base-18-ea+8-linux-arm32.jar
For linux:
  https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+8/javafx-media-18-ea+8-linux.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-controls/18-ea+8/javafx-controls-18-ea+8-linux.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/18-ea+8/javafx-graphics-18-ea+8-linux.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-base/18-ea+8/javafx-base-18-ea+8-linux.jar
For mac-aarch64:
  https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+8/javafx-media-18-ea+8-mac-aarch64.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-controls/18-ea+8/javafx-controls-18-ea+8-mac-aarch64.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/18-ea+8/javafx-graphics-18-ea+8-mac-aarch64.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-base/18-ea+8/javafx-base-18-ea+8-mac-aarch64.jar
For mac:
  https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+8/javafx-media-18-ea+8-mac.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-controls/18-ea+8/javafx-controls-18-ea+8-mac.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/18-ea+8/javafx-graphics-18-ea+8-mac.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-base/18-ea+8/javafx-base-18-ea+8-mac.jar
For win:
  https://repo1.maven.org/maven2/org/openjfx/javafx-media/18-ea+8/javafx-media-18-ea+8-win.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-controls/18-ea+8/javafx-controls-18-ea+8-win.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/18-ea+8/javafx-graphics-18-ea+8-win.jar
  https://repo1.maven.org/maven2/org/openjfx/javafx-base/18-ea+8/javafx-base-18-ea+8-win.jar
  
  Just took the code and run through JShell, and got all the links.
