### ISSUE TITLE
Cyclic hierarchy 3.X

### ISSUE THREAD

**Issue by darklol9** [Col-E/Recaf#616]
**Describe the bug**

Classes with reoccurring hierarchy bug out the workspace viewer on 3.X,

**To Reproduce**

1. Create class A which extends a class B
2. Create the class B and have it extend class A
3. View this jar using Recaf 3.X and it will bug the workspace panel

**Exception**

When opening the jar
```
org.clyze.jphantom.hier.CyclicHierarchyException: ([java.lang.System, java.lang.CharSequence, java.lang.String, java.lang.Object, java.util.Iterator, java.io.FilterOutputStream, java.io.Flushable, java.io.OutputStream, java.io.Serializable, Test, java.io.Closeable, java.lang.AutoCloseable, java.io.PrintStream, java.util.Scanner, java.lang.Appendable, aefep.cvedx, java.lang.Comparable, aefep.elimp, java.io.InputStream], [(java.lang.System,java.lang.Object), (java.lang.CharSequence,java.lang.Object), (java.lang.String,java.lang.CharSequence), (java.lang.String,java.io.Serializable), (java.lang.String,java.lang.Comparable), (java.lang.String,java.lang.Object), (java.util.Iterator,java.lang.Object), (java.io.FilterOutputStream,java.io.OutputStream), (java.io.Flushable,java.lang.Object), (java.io.OutputStream,java.io.Flushable), (java.io.OutputStream,java.io.Closeable), (java.io.OutputStream,java.lang.Object), (java.io.Serializable,java.lang.Object), (Test,java.lang.Object), (java.io.Closeable,java.lang.AutoCloseable), (java.io.Closeable,java.lang.Object), (java.lang.AutoCloseable,java.lang.Object), (java.io.PrintStream,java.lang.Appendable), (java.io.PrintStream,java.io.Closeable), (java.io.PrintStream,java.io.FilterOutputStream), (java.util.Scanner,java.util.Iterator), (java.util.Scanner,java.io.Closeable), (java.util.Scanner,java.lang.Object), (java.lang.Appendable,java.lang.Object), (aefep.cvedx,aefep.elimp), (java.lang.Comparable,java.lang.Object), (aefep.elimp,aefep.cvedx), (java.io.InputStream,java.io.Closeable), (java.io.InputStream,java.lang.Object)])
	at org.clyze.jphantom.hier.graph.GraphConverter.convert(GraphConverter.java:51)
	at org.clyze.jphantom.hier.closure.CopyingSnapshot.<init>(CopyingSnapshot.java:30)
	at org.clyze.jphantom.constraints.extractors.AbstractExtractor.<init>(AbstractExtractor.java:26)
	at org.clyze.jphantom.constraints.extractors.TypeConstraintExtractor.<init>(TypeConstraintExtractor.java:35)
	at org.clyze.jphantom.JPhantom.run(JPhantom.java:80)
	at me.coley.recaf.util.JPhantomUtil.generate(JPhantomUtil.java:76)
	at me.coley.recaf.util.CompileDependencyUpdater.createPhantoms(CompileDependencyUpdater.java:55)
	at me.coley.recaf.util.CompileDependencyUpdater.lambda$install$0(CompileDependencyUpdater.java:37)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

When viewing the package containing these classes
```
java.lang.StackOverflowError
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	...
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
```

**Screenshots**
![panel](https://cdn.upload.systems/uploads/Hrb1KPpc.png)

**File**
https://cdn.discordapp.com/attachments/1000042889239330908/1039251596581806131/output.jar

**Comment by Amejonah1200** [comment]
![image](https://user-images.githubusercontent.com/50181314/200403016-f4cf5dcf-707a-4d86-9669-9cd99f3df1ce.png)

**Comment by Col-E** [comment]
8db68afafab2b19190de03c4ec3dee732a4cdf3e

**Comment by Col-E** [comment]
JPhantom is just being JPhantom. The hierarchy stuff we do though has been updated.
