### ISSUE TITLE
NPE on startup, fails to load program.

### ISSUE THREAD

**Issue by dudeedud4** [Col-E/Recaf#62]
**Describe the bug**

> Just straight up fails to load due to updater.java

```
C:\Users\panda\Desktop\hecks\REC Cracking Toolkit 3-11\Java Recaf>java -jar recaf-1.2.1.jar
Exception in thread "main" java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
        at com.google.common.io.Resources$UrlByteSource.<init>(Resources.java:67)
        at com.google.common.io.Resources$UrlByteSource.<init>(Resources.java:62)
        at com.google.common.io.Resources.asByteSource(Resources.java:56)
        at com.google.common.io.Resources.asCharSource(Resources.java:88)
        at com.google.common.io.Resources.toString(Resources.java:113)
        at me.coley.recaf.Updater.getVersionFromJar(Updater.java:143)
        at me.coley.recaf.Updater.init(Updater.java:42)
        at me.coley.recaf.Recaf.main(Recaf.java:20)

C:\Users\panda\Desktop\hecks\REC Cracking Toolkit 3-11\Java Recaf>
```

**Comment by Col-E** [comment]
For some reason the file I uploaded is missing the pom in the generated jar. Recompiling from source will fix this, but I'll add additional error handling.

**Comment by Col-E** [comment]
9feb35a0f09471c63b28a60f95192b15c778833e resolved here, will update releases
