### ISSUE TITLE
Crash while opening via console

### ISSUE THREAD

**Issue by MikiP98** [Col-E/Recaf#627]
**Describe the bug**

> Recaf is crashing when started through console

**To Reproduce**

1. Download Recaf (recaf-2.21.13-J8-jar-with-dependencies.jar)
2. Open it via console. Use Eclipse Adoptium java jdk 17.0.5 or 11.0.15
3. See error

**Exception**

If applicable, add the exception/stacktrace.
```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task
        at me.coley.recaf.command.impl.Initializer.run(Initializer.java:60)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at me.coley.recaf.Recaf.launch(Recaf.java:103)
        at me.coley.recaf.Recaf.main(Recaf.java:52)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 11 more

**Screenshots**
![image](https://user-images.githubusercontent.com/79966387/209386581-a1b2344b-9b6d-4e04-8ee6-a3b066f2db66.png)


If applicable, add screenshots to help explain your problem.

**Comment by Col-E** [comment]
https://www.coley.software/Recaf-documentation/use-config.html

Delete the Recaf directory and try again. If it didn't fully download JFX to the local cache it could fail to load them on launch like this.

**Comment by MikiP98** [comment]
Thanks! That helped.
