### ISSUE TITLE
cannot list exported jar file

### ISSUE THREAD

**Issue by xxmfxx** [Col-E/Recaf#630]
**Description**

Cannot view exported jar file, MacOS Monterey

**To Reproduce**

1. Load class file
2. Export program
3. List jar contents

**Exception**

```
$ jar tf exported.jar
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:143)
	at jdk.jartool/sun.tools.jar.Main.extract(Main.java:1373)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:382)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1665)
```

**Comment by Col-E** [comment]
> Load class file

You load in a class, it will export a class. Plop the file in a hex editor or even a text editor and you'll see its a class file, not a zip/jar.

**Comment by xxmfxx** [comment]
I see, thanks.  Save As... pre-populates with "Untitled.jar" regardless.  Shouldn't it pre-populate with the correct extension?

**Comment by Col-E** [comment]
It should, and that's something I think got improved upon in the 3x snapshots. Though I'm reworking a lot of that logic now so I can ensure its a non-issue going forward on 3x.
