### ISSUE TITLE
Cannot edit Assebmbly: Named Variables Sharing Index

### ISSUE THREAD

**Issue by C0D3-M4513R** [Col-E/Recaf#632]
**Describe the bug**

I cannot edit bytecode, for the method `static SNBTCompoundTag read(Path)` in `dev.ftb.mods.ftblibrary.snbt.SNBT`. See attached jar and error.

**To Reproduce**

1. Open sample [ftb-library-forge-1802.3.6-build.140.zip](https://github.com/Col-E/Recaf/files/10517177/ftb-library-forge-1802.3.6-build.140.zip) (rename extension to .jar) (source [here ](https://github.com/FTBTeam/FTB-Library/blob/e23e1c07009c8f6233d950c5f8289d0d98a595a8/common/src/main/java/dev/ftb/mods/ftblibrary/snbt/SNBT.java) (possibly not the exact commit, but probably close enough for demo purposes))
2. Navigate to 'dev.ftb.mods.ftblibrary.snbt.SNBT'
3. Open the assembly for the method `static SNBTCompoundTag read(Path)`

**Exception**
```
10:04:07.949 [main] WARN : Failed to delete old log file, will append instead
10:04:07.951 [main] INFO : Recaf-2.21.13
10:04:07.952 [main] INFO : - Java: 18.0.2.1 (Java HotSpot(TM) 64-Bit Server VM)
10:04:08.053 [main] TRACE: Loading configuration
Jan 27, 2023 10:04:08 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @34c45dca'
10:04:37.641 [ForkJoinPool-1-worker-1] INFO : Loaded workspace from: ftb-library-forge-1802.3.6-build.140.jar
10:04:37.641 [ForkJoinPool-1-worker-2] DEBUG: Begin generating phantom classes, given 247 input classes
10:04:38.344 [ForkJoinPool-1-worker-2] DEBUG: Phantom analysis complete, generated 247 classes
10:04:38.345 [ForkJoinPool-1-worker-2] DEBUG: Generated 304 phantom classes in 704 ms
10:04:50.834 [JavaFX Application Thread] WARN : Separating variables of same name pointing to different indices: read(Ljava/nio/file/Path;)Ldev/ftb/mods/ftblibrary/snbt/SNBTCompoundTag;
10:04:51.361 [Recaf Scheduler Thread #1] WARN : Separating variables of same name pointing to different indices: read(Ljava/nio/file/Path;)Ldev/ftb/mods/ftblibrary/snbt/SNBTCompoundTag;
10:04:51.379 [Recaf Scheduler Thread #1] ERROR: Unrecognized exception thrown when assembling method
me.coley.recaf.parse.bytecode.exception.AssemblerException: Named variables sharing the same index is not yet supported in Recaf's assembler
The disassembler should have de-duplicated the indices. Please open a bug report.
        at me.coley.recaf.parse.bytecode.VariableGenerator.computeVariables(VariableGenerator.java:85)
        at me.coley.recaf.parse.bytecode.MethodAssembler.compile(MethodAssembler.java:117)
        at me.coley.recaf.ui.controls.text.BytecodeEditorPane.lambda$null$0(BytecodeEditorPane.java:88)
        at me.coley.recaf.ui.controls.text.ErrorHandling.lambda$onCodeChange$0(ErrorHandling.java:93)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
**Screenshots**
![grafik](https://user-images.githubusercontent.com/28912031/215047482-bc86a8c9-0796-4bbf-962c-3245a268b253.png)

**Comment by Amejonah1200** [comment]
Please try this with Recaf 3x:
- build yourself from the dev3 branch here (recommended)
- take snapshot: https://github.com/Col-E/recaf-3x-issues/releases

**Comment by Col-E** [comment]
For the second issue on 3x, could you open a new issue so its tracked separately?

I believe this is a known issue being worked on already by @Nowilltolife
