### ISSUE TITLE
Hierarchy method renaming tends to fail on larger jars

### ISSUE THREAD

**Issue by Col-E** [Col-E/Recaf#65]
When remapping methods on small inputs, the method hierarchy is renamed successfully.
When introducing a thousand or so extra/unrelated classes renaming the same method fails to update the hierarchy

> _Linked method renaming_ feature success is conditional 

**To Reproduce**
1. Compile recaf from src and then use the smaller jar as input.
2. Use _Linked method renaming_ and rename `me/coley/logging/Logger.write(Ljava/lang/String;)V` to anything
    * It should rename, and so should `me/coley/logging/ConsoleLogger.write(Ljava/lang/String;)V`
2. Use the larger jar with dependencies as input.
2. Use _Linked method renaming_ and rename `me/coley/logging/Logger.write(Ljava/lang/String;)V` to anything
    * It does not rename, and nor does `me/coley/logging/ConsoleLogger.write(Ljava/lang/String;)V`

**Comment by Col-E** [comment]
Looks like the bug was caused by something else:

```
java.lang.IllegalArgumentException: JSR/RET are not supported with computeFrames option
	at org.objectweb.asm.Frame.execute(Frame.java:1009)
	at org.objectweb.asm.MethodWriter.visitJumpInsn(MethodWriter.java:1147)
	at org.objectweb.asm.tree.JumpInsnNode.accept(JumpInsnNode.java:80)
	at org.objectweb.asm.tree.InsnList.accept(InsnList.java:145)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:789)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:687)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:436)
	at me.coley.recaf.bytecode.Asm.getBytes(Asm.java:77)
	at me.coley.recaf.Input$4.castBytes(Input.java:769)
	at me.coley.recaf.Input$4.castBytes(Input.java:1)
	at me.coley.recaf.Input$FileMap.put(Input.java:1000)
	at me.coley.recaf.Input.onMethodRename(Input.java:267)
```

**Comment by Col-E** [comment]
So the actual issue was there were certain classes in the jar that were compiled with an older version and hence contained older opcodes that are no longer supported. Recaf tried to generate stack-frames for the opcode which failed due to ASM's implementation.

Possible future approaches:

* Plugin to replace JSR/RET opcodes so this does not happen
* Auto-detect when to not use `COMPUTE_FRAMES` even when the option is enabled

**Comment by andrewleech** [comment]
Hi, I seem to be getting the same issue when trying to edit some bytecode in an older jar
```
08:19:58.143 [JavaFX Application Thread] ERROR: Uncaught exception when assembling method
java.lang.IllegalArgumentException: JSR/RET are not supported with computeFrames option
	at org.objectweb.asm.Frame.execute(Frame.java:1017)
	at org.objectweb.asm.MethodWriter.visitJumpInsn(MethodWriter.java:1145)
	at org.objectweb.asm.tree.JumpInsnNode.accept(JumpInsnNode.java:79)
	at org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:751)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at me.coley.recaf.ui.controls.text.BytecodeEditorPane.assemble(BytecodeEditorPane.java:230)
	at me.coley.recaf.ui.controls.view.BytecodeViewport.save(BytecodeViewport.java:85)
	at me.coley.recaf.ui.controls.view.EditorViewport.handleKeyReleased(EditorViewport.java:53)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:4098)
	at javafx.scene.Scene.processKeyEvent(Scene.java:2157)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2625)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
	at com.sun.glass.ui.View.notifyKey(View.java:971)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Is there a workaround I can try for this with Recaf 2.17.5? Would running on an older Java help (I've got jdk-14.0.2) or is there a way to manually turn off `COMPUTE_FRAMES` ? Thanks!

**Comment by Col-E** [comment]
You can turn off `verify` in the assembler config.

I also should add a JSR inliner into the loading logic to prevent the need to do this.

**Comment by andrewleech** [comment]
Thanks for the suggestion, I've just started trying out recaf and so far love the work you've put into it!
