### ISSUE TITLE
Some of classes does not decompile properly

### ISSUE THREAD

**Issue by emsar69** [Col-E/Recaf#656]
i got this while trying to decompile 37mb jar file

![image](https://github.com/Col-E/Recaf/assets/72223726/76d343c7-42fc-4fd8-ba44-3ec7da124f9e)

My log:

16:52:48.094 [main] INFO : Recaf-2.21.13
16:52:48.096 [main] INFO : - Java: 18.0.2.1 (Java HotSpot(TM) 64-Bit Server VM)
Jul 23, 2023 4:52:48 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @66a29884'
16:53:08.205 [ForkJoinPool-1-worker-1] DEBUG: Skipping duplicate class 'org/jetbrains/java/decompiler/util/ClasspathScanner'
16:53:08.585 [ForkJoinPool-1-worker-1] DEBUG: Skipping duplicate class 'module-info'
16:53:08.658 [ForkJoinPool-1-worker-1] DEBUG: Invalid class detected, not parsable by backup reader "com/sun/jna/darwin-x86-64/libjnidispatch.jnilib"
16:53:08.659 [ForkJoinPool-1-worker-1] DEBUG: Invalid class detected, not parsable by backup reader "com/sun/jna/darwin-aarch64/libjnidispatch.jnilib"
16:53:08.795 [ForkJoinPool-1-worker-1] DEBUG: Skipping duplicate class 'org/fxmisc/richtext/JavaFXCompatibility'
16:53:08.795 [ForkJoinPool-1-worker-1] DEBUG: Skipping duplicate class 'org/fxmisc/richtext/TextFlowExt'
16:53:08.947 [ForkJoinPool-1-worker-1] INFO : Loaded workspace from: recaf-2.21.13-J8-jar-with-dependencies.jar
16:53:08.947 [ForkJoinPool-1-worker-2] DEBUG: Begin generating phantom classes, given 10966 input classes
16:53:20.262 [ForkJoinPool-1-worker-2] ERROR: Failed to analyze phantom references for primary resource
org.clyze.jphantom.exc.IllegalBytecodeException: Instruction: 54
        at org.clyze.jphantom.exc.IllegalBytecodeException$Builder.build(IllegalBytecodeException.java:84)
        at org.clyze.jphantom.constraints.extractors.TypeConstraintExtractor.visit(TypeConstraintExtractor.java:113)
        at org.clyze.jphantom.constraints.extractors.TypeConstraintExtractor.visit(TypeConstraintExtractor.java:46)
        at org.clyze.jphantom.JPhantom.run(JPhantom.java:84)
        at me.coley.recaf.workspace.PhantomResource.populatePhantoms(PhantomResource.java:98)
        at me.coley.recaf.workspace.Workspace.lambda$analyzePhantoms$0(Workspace.java:160)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.clyze.jphantom.exc.InsolvableConstraintException: java.util.Map$Entry <: com.google.common.collect.ImmutableMapEntry
        at org.clyze.jphantom.constraints.extractors.AbstractExtractor.visit(AbstractExtractor.java:79)
        at org.clyze.jphantom.conversions.WideningReferenceConversion.accept(WideningReferenceConversion.java:13)
        at org.clyze.jphantom.constraints.extractors.TypeConstraintExtractor$MethodConstraintExtractor.addConstraint(TypeConstraintExtractor.java:587)
        at org.clyze.jphantom.constraints.extractors.TypeConstraintExtractor$MethodConstraintExtractor.visitInsn(TypeConstraintExtractor.java:226)
        at org.objectweb.asm.tree.InsnNode.accept(InsnNode.java:65)
        at org.objectweb.asm.tree.InsnList.accept(InsnList.java:144)
        at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:751)
        at org.clyze.jphantom.constraints.extractors.TypeConstraintExtractor.visit(TypeConstraintExtractor.java:105)
        ... 10 common frames omitted
16:54:37.258 [ForkJoinPool-1-worker-1] DEBUG: Invalid class detected, not parsable by backup reader "com/sun/jna/darwin/libjnidispatch.jnilib"
16:54:37.727 [ForkJoinPool-1-worker-1] INFO : Loaded workspace from: launcher.jar
16:54:37.727 [ForkJoinPool-1-worker-2] DEBUG: Begin generating phantom classes, given 7326 input classes
16:54:43.415 [ForkJoinPool-1-worker-2] DEBUG: Phantom analysis complete, generated 7326 classes
16:54:43.416 [ForkJoinPool-1-worker-2] DEBUG: Generated 516 phantom classes in 5689 ms
16:57:01.360 [JavaFX Application Thread] DEBUG: Using default editor for value 'binding.swapview', type: me.coley.recaf.config.ConfKeybinding$Binding
16:57:01.361 [JavaFX Application Thread] DEBUG: Using default editor for value 'binding.incfontsize', type: me.coley.recaf.config.ConfKeybinding$Binding
16:57:01.361 [JavaFX Application Thread] DEBUG: Using default editor for value 'binding.decfontsize', type: me.coley.recaf.config.ConfKeybinding$Binding

**Comment by Col-E** [comment]
We don't write the decompilers, we just plug them in and add our own capabilities on top.

1. The red error indicators in the UI are from our JavaParser logic, saying that it can't parse the source into an AST. More info on how to handle situations like this on the docs: https://www.coley.software/Recaf-documentation/use-editing.html
2. The error in the log from JPhantom is associated with recompilation, but you won't be recompiling obfuscated code anyways so it doesn't really matter that it failed.
