### ISSUE TITLE
Can't launch recaf on linux

### ISSUE THREAD

**Issue by huanmoon** [Col-E/Recaf#661]
**Describe the bug**

> I'm using archlinux and try to launch recaf through console but it failed.And I try to launch it on Windows through console,it works.

[huan_moon@Void Downloads]$ java -jar recaf-2.21.13-J8-jar-with-dependencies.jar 
22:27:05.425 [main] INFO : Recaf-2.21.13
22:27:05.427 [main] INFO : - Java: 17.0.8 (OpenJDK 64-Bit Server VM)
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/concurrent/Task
        at me.coley.recaf.command.impl.Initializer.run(Initializer.java:60)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at me.coley.recaf.Recaf.launch(Recaf.java:103)
        at me.coley.recaf.Recaf.main(Recaf.java:52)
Caused by: java.lang.ClassNotFoundException: javafx.concurrent.Task
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 11 more

**To Reproduce**

1. Download 'recaf-2.21.13-J8-jar-with-dependencies.jar'
2.Run <code>java -jar recaf-2.21.13-J8-jar-with-dependencies.jar </code>

**Comment by xxDark** [comment]
Delete cache folder in Recaf's directory

**Comment by huanmoon** [comment]
> Delete cache folder in Recaf's directory

sorry but there is no folder called cache in Recaf's directory

**Comment by xxDark** [comment]
'dependencies' it is then

**Comment by huanmoon** [comment]
> 'dependencies' it is then

no dependencies too

**Comment by Amejonah1200** [comment]
Just delete the folder where there are javafx jars in it

**Comment by Col-E** [comment]
Just to be clear, the recaf directory isn't the directory where recaf is in when you run it.

See the config doc page for locations per OS: https://www.coley.software/Recaf-documentation/use-config.html

**Comment by huanmoon** [comment]
> Just to be clear, the recaf directory isn't the directory where recaf is in when you run it.
> 
> See the config doc page for locations per OS: https://www.coley.software/Recaf-documentation/use-config.html

it works, thanks
