### ISSUE TITLE
ServiceConfigurationError when upgrading logback 1.2.10 --> 1.4.X

### ISSUE THREAD

**Issue by Soxs** [Col-E/Recaf#711]
When loading Recaf with JDK11 I get this stracktrace:

This is snapshot 15

> "C:\Program Files\Java\jdk-11.0.4\bin\java.exe" -jar recaf3.jar
> Exception in thread "main" java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: Provider ch.qos.logback.classic.spi.LogbackServiceProvider not found
>         at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
>         at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)
>         at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
>         at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
>         at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
>         at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
>         at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:104)
>         at org.slf4j.LoggerFactory.bind(LoggerFactory.java:147)
>         at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139)
>         at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:422)
>         at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:408)
>         at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
>         at me.coley.recaf.util.logging.Logging.lambda$get$1(Logging.java:45)
>         at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
>         at me.coley.recaf.util.logging.Logging.get(Logging.java:45)
>         at me.coley.recaf.Main.<clinit>(Main.java:30)

**Comment by Col-E** [comment]
e78256d69013468dbeae664e9d9adbf7aef47b91 - Tired of logback being weird with random updates. Replaced with simpler/leaner logger impl.
