### ISSUE TITLE
Java 10 cannot run recaf

### ISSUE THREAD

**Issue by BullyWiiPlaza** [Col-E/Recaf#72]
If `recaf` is started using a `JRE 10` or higher, it will not load. Also, "illegal" reflections are being made (according to the console output). You may want to fix those as well.

1. [Install `Java 10`](http://www.oracle.com/technetwork/java/javase/downloads/jre10-downloads-4417026.html)
2. Run recaf via `java -jar recaf.jar`
3. It does not start and throw many errors/exceptions on the console output

```
$ java -jar recaf-1.5.0.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.coley.recaf.util.Reflect (file:/D:/Recaf/recaf-1.5.0.jar) to method java.lang.Class.privateGetDeclaredFields(boolean)
WARNING: Please consider reporting this to the maintainers of me.coley.recaf.util.Reflect
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.NoClassDefFoundError: com/sun/tools/attach/VirtualMachine
        at me.coley.recaf.util.Misc.isJDK(Misc.java:21)
        at me.coley.recaf.ui.FxWindow.start(FxWindow.java:68)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 11 more
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/scene/control/skin/ListViewSkin
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at me.coley.recaf.ui.FxWindow$LogPane.<init>(FxWindow.java:1024)
        at me.coley.recaf.ui.FxWindow.start(FxWindow.java:92)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.scene.control.skin.ListViewSkin
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 20 more
Exception in thread "Thread-1" Exception in thread "Thread-6" java.lang.NoClassDefFoundError: sun/reflect/FieldAccessor
        at me.coley.recaf.util.Reflect.get(Reflect.java:110)
        at me.coley.recaf.config.Config.save(Config.java:59)
        at me.coley.recaf.config.Config.lambda$addSaveHook$0(Config.java:187)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: sun.reflect.FieldAccessor
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
Exception in thread "Thread-0" Exception in thread "Thread-5" java.lang.NoClassDefFoundError: sun/reflect/FieldAccessor
        at me.coley.recaf.util.Reflect.get(Reflect.java:110)
        at me.coley.recaf.config.Config.save(Config.java:59)
        at me.coley.recaf.config.Config.lambda$addSaveHook$0(Config.java:187)
        at java.base/java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: sun/reflect/FieldAccessor
        at me.coley.recaf.util.Reflect.get(Reflect.java:110)
        at me.coley.recaf.config.Config.save(Config.java:59)
        at me.coley.recaf.config.Config.lambda$addSaveHook$0(Config.java:187)
        at java.base/java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: sun/reflect/FieldAccessor
        at me.coley.recaf.util.Reflect.get(Reflect.java:110)
        at me.coley.recaf.config.Config.save(Config.java:59)
        at me.coley.recaf.config.Config.lambda$addSaveHook$0(Config.java:187)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Col-E** [comment]
I've not yet installed java 10 but I got a sense of how I'm going to fix it *(multi-release jar with version-specific logic)*.

I'm away for the weekend though, so I can't address this until I get back. If you still have JDK-8 you can manually specify their `java.exe` until I fix this.

**Comment by BullyWiiPlaza** [comment]
@Col-E Yes, I use `Java 8` for development and `Java 10` for running Java programs. Manually specifying Java 8 works of course.

**Comment by Col-E** [comment]
So I have everything working on JDK 10 now... The only issue is how to handle what people have on their local machines. I do not want to force people to have to download a new JDK. Looking into ways to efficiently bundle future releases.

**Comment by Col-E** [comment]
https://col-e.github.io/Recaf/documentation.html#gs-r

Going to close this for now. Releases are JDK 8 based. The only thing you need to do to use Java 9, 10, ... is to update the `ControlsFX` dependency. I feel that most people are going to stick to JDK 8 for a while so I'm not going to force the update any time soon.
