### ISSUE TITLE
Remote connection does not respond with classloader/class data on Java 14+

### ISSUE THREAD

**Issue by Col-E** [Col-E/Recaf#730]
Works on Java 8, 11, does not work on Java 14 or higher

**Comment by Col-E** [comment]
On the remote process when handling packet responses:
```
java.lang.NoClassDefFoundError: Could not initialize class java.util.concurrent.CompletableFuture
        at software.coley.instrument.sock.WriteResult.<init>(WriteResult.java:16)
        at software.coley.instrument.sock.ChannelHandler.write(ChannelHandler.java:135)
        at software.coley.instrument.Server.lambda$answer$13(Server.java:249)
        at software.coley.instrument.Server.lambda$configureChannel$2(Server.java:184)
        at software.coley.instrument.sock.ChannelHandler.lambda$readLoop$2(ChannelHandler.java:202)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
        ```

**Comment by Col-E** [comment]
The error does not occur when running the server with debug enabled which is quite annoying...
