### ISSUE TITLE
Cannot reconnect to previously attached to process

### ISSUE THREAD

**Issue by Col-E** [Col-E/Recaf#731]
Reproduction:

- Connect to a process
- Disconnect
- Try connecting to it again

Trace from Recaf:
```
java.io.IOException: Could not connect to remote JVM 15640 over localhost:24006
	at software.coley.recaf.workspace.model.resource.AgentServerRemoteVmResource.connect(AgentServerRemoteVmResource.java:147)
	at software.coley.recaf.ui.pane.RemoteVirtualMachinesPane$VmPane.lambda$new$0(RemoteVirtualMachinesPane.java:233)
	at software.coley.recaf.util.threading.ThreadUtil.lambda$wrap$2(ThreadUtil.java:222)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at software.coley.recaf.util.threading.ThreadUtil.lambda$wrap$2(ThreadUtil.java:222)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:586)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:853)
	at software.coley.instrument.Client.connectThrowing(Client.java:111)
	at software.coley.recaf.workspace.model.resource.AgentServerRemoteVmResource.connect(AgentServerRemoteVmResource.java:144)
	... 10 more
```

Log from remote process
```java
// starts
[Server][Attach Listener] Opening server on: localhost/127.0.0.1:22255

// Recaf connects
[Server][agent-client-accept-loop 0] New client: java.nio.channels.SocketChannel[connected local=/127.0.0.1:22255 remote=/127.0.0.1:63830]

// Sees request from Recaf, tries to send response but does not (no exception thrown tho...) - Reported in separate issue 730
[Server][agent-read-loop 1] Channel read-header: id=0, type=110, length=0
[Server][agent-read-loop 1] Channel read-body: RequestClassloadersMessage
[Server][agent-event-loop 3] Channel event fire
[Server][agent-event-handling 4] Server handling request[id=0, value=RequestClassloadersMessage]

// Recaf disconnects
[Server][agent-read-loop 1] Closing channel java.nio.channels.SocketChannel[connected local=/127.0.0.1:22255 remote=/127.0.0.1:63830]
[Server][agent-read-loop 1] Disconnect client: java.nio.channels.SocketChannel[connected local=/127.0.0.1:22255 remote=/127.0.0.1:63830]

// Recaf attempts to reconnect, but nothing is seen by the server
```

The issue seems to be due to Recaf's side of handling things AFAIK, as closing Recaf and re-opening allows connecting to the process again.

**Comment by Col-E** [comment]
The port discovery is not kicking in on the remote process, so Recaf thinks it needs to connect using a new port.

It tells the process to start a new server with the agent, but the agent is already loaded on another port.

**Comment by Col-E** [comment]
bc73b3b0bfc7b9a095fca0016823f438c4719775
