### ISSUE TITLE
Recaf on NixOs

### ISSUE THREAD

**Issue by C0D3-M4513R** [Col-E/Recaf#739]
**Describe the bug**
Recaf 2.21.13, latest 3.0.0-SNAPSHOT and recaf-launcher-0.1.3.jar all fail to start Recaf

**To Reproduce**

1. Be on Nixos
2. Download any of the versions I talked about
3. Open a new shell with java inside: `nix-shell -p jdk17 openjfx17`
4. Run the recaf jars
5. See error

**Exception**

<details><summary>log</summary>
<p>

```
Nov 13, 2023 1:41:25 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @66a2429c'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /home/user/.openjfx/cache/22-ea+16/amd64/libprism_es2.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /home/user/.openjfx/cache/22-ea+16/amd64/libprism_es2.so: libXxf86vm.so.1: cannot open shared object file: No such file or directory
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:220)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:200)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:142)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:58)
        at com.sun.prism.es2.ES2Pipeline.lambda$static$0(ES2Pipeline.java:63)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:52)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:92)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.base/java.lang.Thread.run(Thread.java:833)
Loading library glassgtk3 from resource failed: java.lang.UnsatisfiedLinkError: /home/user/.openjfx/cache/22-ea+16/amd64/libglassgtk3.so: libXtst.so.6: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /home/user/.openjfx/cache/22-ea+16/amd64/libglassgtk3.so: libXtst.so.6: cannot open shared object file: No such file or directory
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:220)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:200)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:142)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:58)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(GtkApplication.java:173)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:162)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:40)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:292)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:833)
01:41:26.021 [Main/main] ERROR: Uncaught exception on thread 'main'
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: no glassgtk3 in java.library.path: 
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:300)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:292)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsatisfiedLinkError: no glassgtk3 in java.library.path: 
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1989)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:170)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:58)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(GtkApplication.java:173)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:162)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:40)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
        ... 6 common frames omitted
Weld SE container recaf shut down by shutdown hook
```

</p>
</details>

The core issue here is probably most likely the changes that nix makes to library loading.
Feel free to see this issue as more of a tracking issue.
(I already tried packaging my software for nix, and it wasn't easy)
I made a package request to nix: https://github.com/NixOS/nixpkgs/issues/267124

**Screenshots**

**Comment by Col-E** [comment]
https://github.com/NixOS/nixpkgs/issues/220470

Seems like there was a recent similar issue. It has the same `caused by` block at the end.

**Comment by Col-E** [comment]
I can't really help with things on the native side of thing for an OS I don't run, but hopefully somebody else may have some valuable insight.

**Comment by C0D3-M4513R** [comment]
I understand a lot more now, and I understand, that 4.x will (as it stands right now) NEVER be available in NixOs, due to it requiring a wrapping launcher.

I have not bothered with making 2.x available, since it just does not have the feature-set I am looking for.

**Comment by therathatter** [comment]
> I understand a lot more now, and I understand, that 4.x will (as it stands right now) NEVER be available in NixOs (or at least imo), due to it requiring a wrapping launcher.

The launcher is just used to keep Recaf automatically up to date and to set up JavaFX dependencies, both of which can be done by a package manager. I don't see any reason why it would never be available.

**Comment by Col-E** [comment]
As Rat said, the launcher just does what a package manager should do. Its for users who are looking for an easy solution that sets itself up and makes updating easy.

**Comment by Amejonah1200** [comment]
No one forces you not implement this in nix:

https://github.com/Col-E/Recaf-Launcher/blob/256cab79161784fa0f2855f880e4d7c86fa24163/src/main/java/software/coley/recaf/launch/commands/UpdateJavaFX.java#L175

Just download the JAvaFX deps, assign the JDK and launch using this:
https://github.com/Col-E/Recaf-Launcher/blob/256cab79161784fa0f2855f880e4d7c86fa24163/src/main/java/software/coley/recaf/launch/commands/Run.java#L69-L101

**Comment by C0D3-M4513R** [comment]
[flake.txt](https://github.com/Col-E/Recaf/files/14866170/flake.txt)
This flake should do about the same as [one of my earlier comments](https://github.com/Col-E/Recaf/issues/739#issuecomment-1808192982).
It will let you launch recaf in dev mode, thanks to the `LD_LIBRARY_PATH`.

A ton of lines here are probably unnessesary. I just took something from another project of mine.
I still haven't gotten the file dialoges to work though. Idk how to properly apply the `wrapGAppsHook` to a jar file.

**Comment by C0D3-M4513R** [comment]
@Col-E Can you review #805 when you get the chance?

**Comment by TudbuT** [comment]
The 4.X part of this would be solved by NixOS/nixpkgs#267124.

**Comment by C0D3-M4513R** [comment]
Keep https://github.com/NixOS/nixpkgs/pull/354184 (being blocked by maven hashes not being stable and being platform dependent) and https://github.com/NixOS/nixpkgs/pull/350589 in mind.

Rolling-Release software can (and is) packaged in nixos.

**Comment by TudbuT** [comment]
Of course, but it does present a challenge of being either time consuming to maintain or frequently out of date to some extent. Packaging the launcher does make sense here I feel, but this doesn't mean the application shouldn't *also* be packaged directly :P
