### ISSUE TITLE
Does not run with Java 1.8 (MacOS 10.13)

### ISSUE THREAD

**Issue by milo-trujillo** [Col-E/Recaf#74]
The latest Recaf release crashes on launch on MacOS:

~~~sh
$ java -jar recaf-1.5.1.jar 
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:894)
	at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:56)
	at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:158)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: javafx.scene.control.MenuBar.<init>([Ljavafx/scene/control/Menu;)V
	at me.coley.recaf.ui.FxWindow.start(FxWindow.java:66)
	at com.sun.javafx.application.LauncherImpl$8.run(LauncherImpl.java:837)
	at com.sun.javafx.application.PlatformImpl$7.run(PlatformImpl.java:335)
	at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:301)
	at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:298)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl$6.run(PlatformImpl.java:298)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

$ java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
~~~

**Comment by Col-E** [comment]
Can you update your java to the latest version of java 8? 

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

I just downloaded it and when I disassembled `javafx.scene.control.MenuBar` the constructor that it says could not be found was right there:

```
  public javafx.scene.control.MenuBar(javafx.scene.control.Menu...);
    descriptor: ([Ljavafx/scene/control/Menu;)V
    flags: ACC_PUBLIC, ACC_VARARGS
```

If you cannot update java _(lack of perms, etc.)_ can you upload your JavaFX library? It's `jfxrt.jar`

**Comment by Col-E** [comment]
I had a friend with a macbook run recaf under the latest release of Java 8 and it loaded correctly. I'm going to close this with the solution being to update your java package.

**Comment by milo-trujillo** [comment]
Can confirm - updating Java solved the problem here, too. Thanks!
