### ISSUE TITLE
v4 launch issues

### ISSUE THREAD

**Issue by C0D3-M4513R** [Col-E/Recaf#740]
I've had a ton of issues even getting v4 to get as far as it is.
I needed to manually create the dependencies folder in the Appdata folder and some random trial and error.
```
C:\Users\user\Downloads>java -jar recaf-launcher-0.1.3.jar auto
Attempting to resolve installed Recaf version...
Found Recaf's build config, checking contents...
 - MAVEN_GROUP = software.coley
 - MAVEN_NAME = recaf-core
 - VERSION = 4.0.0-SNAPSHOT
 - GIT_REVISION = 1
 - GIT_SHA = 95bfd6142f92fd09493aea916d2a9035c857ce99
 - GIT_DATE = 2023 11/05 05:44
 - GIT_BRANCH = dev4
 - BUILD_DATE = 2023 11/05 05:45
 - BUILD_UNIX_TIME = 1699163124326
 - DIRTY = 0
Attempting to resolve JFX version...
No JavaFX version class found in the current classpath
Java Properties:
 - java.home = C:\Program Files\Eclipse Adoptium\jre-21.0.1.12-hotspot
 - java.version = 21.0.1
 - java.vm.vendor = Eclipse Adoptium
 - java.vm.version = 21.0.1+12-LTS
 - javafx.platform = win
 - javafx.version = -1
 - os.arch = amd64
 - os.bitness = 64
 - os.name = Windows 10
 - os.processors = 4
 - os.version = 10.0
 - recaf.version = 4.0.0-SNAPSHOT

JFX cache:
 - Files: 20439021
 - Size:  20439021
Updated to JavaFX '22-ea+16'
Recaf CI has 30 artifacts listed, fetching first matching one...
Looking in 'C:\Users\timon\AppData\Roaming\Recaf' for Recaf/dependencies...
Running Recaf '4.0.0-SNAPSHOT' with JavaFX '22-ea+16:win'
23:13:35.609 [AccessPatcher/main] DEBUG: Opening access to all packages
23:13:35.625 [AccessPatcher/main] DEBUG: Patching package reflection restrictions
23:13:35.641 [JFXValidation/main] INFO : JavaFX initialized: 22-ea
23:13:35.641 [Bootstrap/main] INFO : Initializing Recaf 4.0.0-SNAPSHOT
23:13:35.641 [Bootstrap/main] INFO : Creating Recaf CDI container...
23:13:35.641 [Bootstrap/main] INFO : CDI: Adding interceptors & extensions
23:13:35.641 [Bootstrap/main] INFO : CDI: Registering bean packages
23:13:35.641 [Bootstrap/main] INFO : CDI: Running user-defined Consumer<Weld>
23:13:35.641 [Bootstrap/main] INFO : CDI: Initializing...
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type AttachManager with qualifiers @Default
  at injection point [BackedAnnotatedParameter] Parameter 2 of [BackedAnnotatedConstructor] @Inject public software.coley.recaf.ui.window.RemoteVirtualMachinesWindow(@Nonnull RemoteVirtualMachinesPane, @Nonnull AttachManager, @Nonnull AttachManagerConfig)
  at software.coley.recaf.ui.window.RemoteVirtualMachinesWindow.<init>(RemoteVirtualMachinesWindow.java:0)

        at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:379)
        at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:294)
        at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:141)
        at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:163)
        at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:533)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:65)
        at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:63)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
        at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
        at org.jboss.weld.executor.CommonForkJoinPoolExecutorServices.lambda$wrap$0(CommonForkJoinPoolExecutorServices.java:70)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedInterruptibleCallable.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
also that wierd linebreak is also there in my terminal.. it is not a github bug

**Comment by Col-E** [comment]
> I've had a ton of issues even getting v4 to get as far as it is.
> I needed to manually create the dependencies folder in the Appdata folder and some random trial and error.

I see you're using the launcher. If its not doing that for you, open a ticket there.

> Failed to create AttatchManager error

I'm not seeing the issue on my end.

```
C:\Code\Java\Recaf-Launcher\target>java -jar recaf-launcher-0.1.3-shaded.jar auto
Attempting to resolve installed Recaf version...
Found Recaf's build config, checking contents...
 - MAVEN_GROUP = software.coley
 - MAVEN_NAME = recaf-core
 - VERSION = 4.0.0-SNAPSHOT
 - GIT_REVISION = 1
 - GIT_SHA = c618771f9eb0f6e298f255b7a066d802e8813e4f
 - GIT_DATE = 2023 10/27 13:58
 - GIT_BRANCH = dev4
 - BUILD_DATE = 2023 10/27 13:58
 - BUILD_UNIX_TIME = 1698415120254
 - DIRTY = 0
Attempting to resolve JFX version...
No JavaFX version class found in the current classpath
Java Properties:
 - java.home = C:\Program Files\AdoptOpenJDK\jdk-17
 - java.version = 17
 - java.vm.vendor = Oracle Corporation
 - java.vm.version = 17+35-2724
 - javafx.platform = win
 - javafx.version = -1
 - os.arch = amd64
 - os.bitness = 64
 - os.name = Windows 10
 - os.processors = 8
 - os.version = 10.0
 - recaf.version = 4.0.0-SNAPSHOT

JFX cache:
 - Files: 10289309
 - Size:  10289309
Updated to JavaFX '22-ea+16'
Recaf CI has 30 artifacts listed, fetching first matching one...
Looking in 'C:\Users\Matt\AppData\Roaming\Recaf' for Recaf/dependencies...
Running Recaf '4.0.0-SNAPSHOT' with JavaFX '22-ea+16:win'
05:51:06.338 [AccessPatcher/main] DEBUG: Opening access to all packages
05:51:06.348 [AccessPatcher/main] DEBUG: Patching package reflection restrictions
05:51:06.349 [JFXValidation/main] INFO : JavaFX initialized: 22-ea
05:51:06.350 [Bootstrap/main] INFO : Initializing Recaf 4.0.0-SNAPSHOT
05:51:06.350 [Bootstrap/main] INFO : Creating Recaf CDI container...
05:51:06.353 [Bootstrap/main] INFO : CDI: Adding interceptors & extensions
05:51:06.354 [Bootstrap/main] INFO : CDI: Registering bean packages
05:51:06.354 [Bootstrap/main] INFO : CDI: Running user-defined Consumer<Weld>
05:51:06.354 [Bootstrap/main] INFO : CDI: Initializing...
05:51:07.222 [Bootstrap/main] INFO : Recaf CDI container created in 872ms
05:51:07.234 [Main/main] TRACE: Compressing 1 old log files
05:51:07.258 [Lang/main] DEBUG: Found 5 translations
05:51:07.265 [Lang/main] INFO : Loaded translations 'zh_CN'
05:51:07.268 [Lang/main] INFO : Loaded translations 'en_US'
05:51:07.272 [Lang/main] INFO : Loaded translations 'sv_SE'
05:51:07.274 [Lang/main] INFO : Loaded translations 'cs_CZ'
05:51:07.276 [Lang/main] INFO : Loaded translations 'de_DE'
05:51:07.286 [Main/main] INFO : Initialization: No plugins found
Nov 14, 2023 5:51:07 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6321e813'
05:51:07.911 [ScriptManager/JavaFX Application Thread] DEBUG: Script created: C:\Users\Matt\AppData\Roaming\Recaf\scripts\anno-adder.java
05:51:07.937 [ScriptManager/JavaFX Application Thread] DEBUG: Script created: C:\Users\Matt\AppData\Roaming\Recaf\scripts\downgrade.java
05:51:07.938 [ScriptManager/JavaFX Application Thread] DEBUG: Script created: C:\Users\Matt\AppData\Roaming\Recaf\scripts\dump.java
05:51:07.939 [ScriptManager/JavaFX Application Thread] DEBUG: Script created: C:\Users\Matt\AppData\Roaming\Recaf\scripts\stripper.java
05:51:07.940 [ScriptManager/JavaFX Application Thread] DEBUG: Starting script directory watch task
05:51:09.096 [WindowManager/JavaFX Application Thread] DEBUG: Register stage: system-information
05:51:09.116 [WindowManager/JavaFX Application Thread] DEBUG: Register stage: mapping-progress
05:51:09.117 [WindowManager/JavaFX Application Thread] DEBUG: Register stage: script-manager
05:51:09.126 [WindowManager/JavaFX Application Thread] DEBUG: Register stage: remote-vms
05:51:09.247 [WindowManager/JavaFX Application Thread] DEBUG: Register stage: config
05:51:09.249 [WindowManager/JavaFX Application Thread] DEBUG: Register stage: main
05:51:09.253 [RecafURLStreamHandlerProvider/JavaFX Application Thread] TRACE: Installed Recaf URL stream handler
05:51:11.332 [WindowManager/JavaFX Application Thread] TRACE: Stage showing: remote-vms
05:51:11.390 [BasicAttachManager/Recaf misc-4] DEBUG: Remote JVM descriptor found (attach-success): 1136 - org.jetbrains.idea.maven.server.RemoteMavenServer36
05:51:11.398 [BasicAttachManager/Recaf misc-5] DEBUG: Remote JVM descriptor found (attach-success): 6504 - org.jetbrains.idea.maven.server.RemoteMavenServer36
05:51:11.399 [BasicAttachManager/Recaf misc-2] DEBUG: Remote JVM descriptor found (attach-success): 2140 - org.jetbrains.idea.maven.server.RemoteMavenServer36
05:51:11.399 [BasicAttachManager/Recaf misc-3] DEBUG: Remote JVM descriptor found (attach-success): 5020 - ?
05:51:11.400 [BasicAttachManager/Recaf misc-0] DEBUG: Remote JVM descriptor found (attach-success): 11404 - org.jetbrains.jps.cmdline.Launcher C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/plugins/java/lib/jps-builders.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/plugins/java/lib/jps-builders-6.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/plugins/java/lib/jps-javac-extension.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/util.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/util-8.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/util_rt.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/annotations.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/3rd-party-rt.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/protobuf.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/jps-model.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/plugins/ja
05:51:11.400 [BasicAttachManager/Recaf misc-1] DEBUG: Remote JVM descriptor found (attach-success): 2696 - org.jetbrains.jps.cmdline.Launcher C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/plugins/java/lib/jps-builders.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/plugins/java/lib/jps-builders-6.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/plugins/java/lib/jps-javac-extension.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/util.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/util-8.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/util_rt.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/annotations.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/3rd-party-rt.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/protobuf.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/lib/jps-model.jar;C:/Program Files/JetBrains/IntelliJ IDEA Community Edition 2022.3.1/plugins/ja
05:51:11.533 [BasicAttachManager/Recaf misc-4] DEBUG: Remote JVM descriptor found (attach-success): 7932 - recaf-launcher-0.1.3-shaded.jar auto
05:51:13.746 [WindowManager/JavaFX Application Thread] TRACE: Stage hiding: remote-vms
05:51:14.588 [WindowManager/JavaFX Application Thread] TRACE: Stage hiding: main
Weld SE container recaf shut down by shutdown hook
```
