### ISSUE TITLE
Unable to open Kotlin classes in Assembler

### ISSUE THREAD

**Issue by 036** [Col-E/Recaf#772]
**Describe the bug**

Edit class in disassembler fails on Kotlin non-obfuscated samples in the latest Dev4

**To Reproduce**

1. Open a jar that has been built using Kotlin.
2. Navigate to any class
3. Edit class in Assembler

**Exception**

```
10:54:47.741 [JvmAssemblerPipeline/ForkJoinPool.commonPool-worker-14] ERROR: Uncaught error creating class printer for: common/behaviour/leafs/DropItems
java.lang.IllegalArgumentException: Cannot convert [I@70ba1b54 into annotation element
        at dev.xdark.blw.asm.internal.Util.wrapElement(Util.java:193)
        at dev.xdark.blw.asm.internal.AsmAnnotationVisitor.visit(AsmAnnotationVisitor.java:19)
        at org.objectweb.asm.ClassReader.readElementValue(ClassReader.java:3157)
        at org.objectweb.asm.ClassReader.readElementValues(ClassReader.java:3009)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:609)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:425)
        at dev.xdark.blw.asm.internal.InternalAsmLibrary.read(InternalAsmLibrary.java:82)
        at dev.xdark.blw.asm.AsmBytecodeLibrary.read(AsmBytecodeLibrary.java:22)
        at me.darknet.assembler.printer.JvmClassPrinter.<init>(JvmClassPrinter.java:34)
        at software.coley.recaf.services.assembler.JvmAssemblerPipeline.classPrinter(JvmAssemblerPipeline.java:161)
        at software.coley.recaf.services.assembler.JvmAssemblerPipeline.disassemble(JvmAssemblerPipeline.java:79)
        at software.coley.recaf.services.assembler.AssemblerPipeline.disassemble(AssemblerPipeline.java:173)
        at software.coley.recaf.services.assembler.JvmAssemblerPipeline$Proxy$_$$_WeldClientProxy.disassemble(Unknown Source)
        at software.coley.recaf.ui.pane.editing.assembler.AssemblerPane.lambda$disassemble$12(AssemblerPane.java:300)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Screenshots**

![image](https://github.com/Col-E/Recaf/assets/17926309/1f307e85-b231-4250-ace0-c4ce79fb90ec)

**Comment by Col-E** [comment]
a041775184efa64012142632ee14b1a1d6cec1fd
