### ISSUE TITLE
Recaf SRG mappings Broken

### ISSUE THREAD

**Issue by neilhuang007** [Col-E/Recaf#789]
Recaf 4.X cannot apply srg mappings 
error logs:18:30:47.373 [MappingMenu/mapping-import-0] INFO : Loaded mappings from vanilla.srg in SRG format
18:30:47.377 [MappingMenu/mapping-import-0] ERROR: Failed to read mappings from vanilla.srg
java.lang.NullPointerException: 'desc' must not be null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at software.coley.recaf.services.mapping.MappingsAdapter.addField(MappingsAdapter.java:292)
	at software.coley.recaf.services.mapping.MappingsAdapter.importIntermediate(MappingsAdapter.java:70)
	at software.coley.recaf.services.mapping.MappingApplier.enrich(MappingApplier.java:126)
	at software.coley.recaf.services.mapping.MappingApplier.applyToPrimaryResource(MappingApplier.java:100)
	at software.coley.recaf.services.mapping.MappingApplier$Proxy$_$$_WeldClientProxy.applyToPrimaryResource(Unknown Source)
	at software.coley.recaf.ui.menubar.MappingMenu.lambda$new$0(MappingMenu.java:89)
	at software.coley.recaf.util.threading.ThreadUtil.lambda$wrap$2(ThreadUtil.java:222)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.

lang.Thread.run(Thread.java:1570)
the srg mappings:
[mapoings.zip](https://github.com/Col-E/Recaf/files/15219477/mapoings.zip)

the class bytes:

[bfk.zip](https://github.com/Col-E/Recaf/files/15219487/bfk.zip)

**Comment by neilhuang007** [comment]
If you try with versions 2.X, it will work

**Comment by Col-E** [comment]
The mappings provided do not throw the NPE you'be listed with the class file you've given in 4.X

I assume some other class is causing the problem to occur. What game version are you targeting?

**Comment by neilhuang007** [comment]
and i am using the newest github dev branch, could it be the issue with that?
here is a small video of me applying it, am i doing it right?
also here is the class file with the mappings
[stuff.zip](https://github.com/Col-E/Recaf/files/15263605/stuff.zip)


https://github.com/Col-E/Recaf/assets/102778463/6d4efec8-dd56-40c5-99c6-0df6d19e5e7e

mabye its my issue with the branch or its a generic issue?

**Comment by Col-E** [comment]
I'm not sure why I don't see the same issue on `dev4` with the files you've originally provided but I did notice the field names weren't being applied. I'll push up the fix for that in a bit and it may also solve this NPE problem as well.

The gist is the mapping applier assumes all formats have fields declare what type they are, but SRG does not. Making the applier aware of this instead of assuming they all support it should work.

**Comment by Col-E** [comment]
Going to close with the changes made to the mapping applier. If this still happens please re-open the ticket with a sample that reproduces the problem with the latest commit.
