### ISSUE TITLE
ERROR: Failed to analyze phantom references for primary resource java.lang.IllegalStateException: null

### ISSUE THREAD

**Issue by 1470429149** [Col-E/Recaf#796]
When I try to open a jar file I get the error
I used recaf-2.21.14-J8-jar-with-dependencies.jar
java 21

C:\Users\Administrator\Desktop\bash>java -jar recaf-2.21.14-J8-jar-with-dependencies.jar
07:04:50.870 [main] INFO : Recaf-2.21.14
07:04:50.872 [main] INFO : - Java: 21.0.3 (OpenJDK 64-Bit Server VM)
07:04:50.955 [main] TRACE: Loading configuration
May 25, 2024 7:04:51 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @255316f2'
07:05:18.171 [ForkJoinPool-1-worker-1] DEBUG: Invalid class detected, not parsable by backup reader "me/lucko/shadow/Method.class"
07:05:18.180 [ForkJoinPool-1-worker-1] INFO : Loaded workspace from: MythicDungeons.jar
07:05:18.181 [ForkJoinPool-1-worker-2] DEBUG: Begin generating phantom classes, given 1079 input classes
07:05:19.535 [ForkJoinPool-1-worker-2] DEBUG: Phantom analysis complete, generated 1079 classes
07:05:19.897 [ForkJoinPool-1-worker-2] ERROR: Failed to analyze phantom references for primary resource
java.lang.IllegalStateException: null
at org.clyze.jphantom.methods.MethodLookupTable$CachingAdapter.visit(MethodLookupTable.java:74)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.SuperclassAdapter.visit(SuperclassAdapter.java:27)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.InterfaceAdder.visit(InterfaceAdder.java:30)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.SuperclassAdapter.visit(SuperclassAdapter.java:27)
at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
at org.clyze.jphantom.adapters.InterfaceAdder.visit(InterfaceAdder.java:30)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:570)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:425)
at org.clyze.jphantom.Transformer.transform(Transformer.java:53)
at org.clyze.jphantom.Phantoms.generateClasses(Phantoms.java:57)
at org.clyze.jphantom.JPhantom.run(JPhantom.java:116)
at me.coley.recaf.workspace.PhantomResource.populatePhantoms(PhantomResource.java:105)
at me.coley.recaf.workspace.Workspace.lambda$analyzePhantoms$0(Workspace.java:160)
at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

Unzip the file and change to jar test：

[MythicDungeons.jar.zip](https://github.com/Col-E/Recaf/files/15494265/MythicDungeons.jar.zip)

**Comment by xcfrg** [comment]
Recaf 2.x is no longer supported, use 4.x: https://github.com/Col-E/Recaf-Launcher

**Comment by Col-E** [comment]
Its an error you can ignore if you don't intend to use recompilation and opt to use the assembler instead.

As per other issues we won't be addressing any issues targeting 2.X
