### ISSUE TITLE
WARNING: Timeout while waiting for app reactivation

### ISSUE THREAD

**Issue by rggu2zr** [Col-E/Recaf#810]
There was no problem when I started it for the first time. When I set the light theme, the interface was messed up, and it couldn't start the second time, showing the following error.
```
java -jar recaf-2.21.14-J8-jar-with-dependencies.jar
12:25:38.781 [main] INFO : Recaf-2.21.14
12:25:38.782 [main] INFO : - Java: 11.0.21 (Java HotSpot(TM) 64-Bit Server VM)
12:25:38.830 [main] TRACE: Loading configuration
Jun 21, 2024 12:25:39 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @60f82f98'
Jun 21, 2024 12:25:44 PM com.sun.glass.ui.mac.MacApplication lambda$waitForReactivation$6
WARNING: Timeout while waiting for app reactivation
```

**Comment by Col-E** [comment]
This is a JavaFX problem on Mac and has been addressed in JavaFX 22 - https://bugs.openjdk.org/browse/JDK-8315657

Using the 4.X snapshots should address it since it pulls in the newest JavaFX version.

**Comment by rggu2zr** [comment]
Seems to have received new questions

https://gluonhq.com/products/javafx/
```
java --module-path javafx-sdk-22.0.1/lib --add-modules javafx.controls,javafx.fxml -jar recaf-2.21.14-J8-jar-with-dependencies.jar
```

Unable to operate bytecode editing, even the right-click event triggered the following error

```
Exception in thread "JavaFX Application Thread" java.lang.reflect.UndeclaredThrowableException
	at org.fxmisc.richtext.$Proxy7.getHitInfo(Unknown Source)
	at org.fxmisc.richtext.TextFlowExt.hit(TextFlowExt.java:140)
	at org.fxmisc.richtext.ParagraphBox.hit(ParagraphBox.java:173)
	at org.fxmisc.richtext.ParagraphBox.hit(ParagraphBox.java:166)
	at org.fxmisc.richtext.ParagraphBox.lambda$stationaryIndices$4(ParagraphBox.java:154)
	at org.reactfx.FlatMapOptStream.lambda$observeInputs$0(FlatMapStream.java:49)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.reactfx.FlatMapOptStream.lambda$observeInputs$0(FlatMapStream.java:49)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.DistinctStream.lambda$observeInputs$0(DistinctStream.java:23)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.EventStream$1.lambda$observeInputs$0(EventStream.java:423)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.MappedStream.lambda$observeInputs$0(MappedStream.java:25)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.FilterStream.lambda$observeInputs$0(FilterStream.java:20)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.SuccessionReducingStream.handleTimeout(SuccessionReducingStream.java:73)
	at org.reactfx.util.FxTimer.lambda$restart$0(FxTimer.java:89)
	at javafx.graphics@22.0.1/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
	at javafx.graphics@22.0.1/com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
	at javafx.graphics@22.0.1/javafx.animation.Timeline.doPlayTo(Timeline.java:172)
	at javafx.graphics@22.0.1/javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at javafx.graphics@22.0.1/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)
	at javafx.graphics@22.0.1/javafx.animation.Animation.doTimePulse(Animation.java:1254)
	at javafx.graphics@22.0.1/javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:208)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@22.0.1/javafx.animation.Animation$1.timePulse(Animation.java:207)
	at javafx.graphics@22.0.1/com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:343)
	at javafx.graphics@22.0.1/com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
	at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:594)
	at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:578)
	at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:571)
	at javafx.graphics@22.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics@22.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.NoSuchMethodException: com.sun.javafx.text.PrismTextLayout.getHitInfo(float,float)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
	at org.fxmisc.richtext.TextFlowExt$GenericIceBreaker.getDeclaredMethod(TextFlowExt.java:279)
	at org.fxmisc.richtext.TextFlowExt$GenericIceBreaker.invoke(TextFlowExt.java:224)
	... 54 more

```

**Comment by xxDark** [comment]
2.x is not supported, as was mentioned before. Try updating richtext to higher version.
