### ISSUE TITLE
Recaf shows invalid representation of  `checkcast` isn's and expects invalid representations

### ISSUE THREAD

**Issue by C0D3-M4513R** [Col-E/Recaf#838]
**Describe the bug**

> A clear and concise description of what the bug is.

Recaf shows `checkcast LL;` instead of the correct `checkcast L`.

**To Reproduce**

Compile the following java code:

```java
public class L {
   public L tryCast(Object o) {
        L l = (L)o;
        return l;
    }
}
```

Then look at the bytecode:
```
    .method public tryCast (Ljava/lang/Object;)LL; {
        parameters: { this, o },
        code: {
        A: 
            line 3
            aload o
            checkcast LL;
            astore l
        B: 
            line 4
            aload l
            areturn 
        C: 
        }
    }
```

In particular: `checkcast LL;`
When you save the class and parse it with `javap -v` you get this:
```
Classfile /home/user/Downloads/L.class
  Last modified Aug 6, 2024; size 380 bytes
  SHA-256 checksum 7512ddb3a0d1dd6822cf48c8f5b4f8922f9b7e771e6bd47e05a29961cbd2a303
  Compiled from "L.java"
public class L
  minor version: 0
  major version: 60
  flags: (0x0021) ACC_PUBLIC, ACC_SUPER
  this_class: #7                          // L
  super_class: #2                         // java/lang/Object
  interfaces: 0, fields: 0, methods: 2, attributes: 1
Constant pool:
   #1 = Methodref          #2.#3          // java/lang/Object."<init>":()V
   #2 = Class              #4             // java/lang/Object
   #3 = NameAndType        #5:#6          // "<init>":()V
   #4 = Utf8               java/lang/Object
   #5 = Utf8               <init>
   #6 = Utf8               ()V
   #7 = Class              #8             // L
   #8 = Utf8               L
   #9 = Utf8               Code
  #10 = Utf8               LineNumberTable
  #11 = Utf8               LocalVariableTable
  #12 = Utf8               this
  #13 = Utf8               LL;
  #14 = Utf8               tryCast
  #15 = Utf8               (Ljava/lang/Object;)LL;
  #16 = Utf8               o
  #17 = Utf8               Ljava/lang/Object;
  #18 = Utf8               l
  #19 = Utf8               SourceFile
  #20 = Utf8               L.java
{
  public L();
    descriptor: ()V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 1: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   LL;

  public L tryCast(java.lang.Object);
    descriptor: (Ljava/lang/Object;)LL;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=3, args_size=2
         0: aload_1
         1: checkcast     #7                  // class L
         4: astore_2
         5: aload_2
         6: areturn
      LineNumberTable:
        line 3: 0
        line 4: 5
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       7     0  this   LL;
            0       7     1     o   Ljava/lang/Object;
            5       2     2     l   LL;
}
SourceFile: "L.java"
```

If you try to change `checkcast LL;`  to `checkcast L` it results in an exception:
```
12:57:58.147 [AssemblerPane/ForkJoinPool.commonPool-worker-19] ERROR: Uncaught exception when assembling contents of Method: main([Ljava/lang/String;)V
java.lang.IllegalStateException: Expected InstanceType
	at dev.xdark.blw.type.TypeReader.read(TypeReader.java:42)
	at me.darknet.assembler.compile.visitor.BlwCodeVisitor.visitTypeInsn(BlwCodeVisitor.java:264)
	at me.darknet.assembler.instructions.jvm.JvmInstructions.lambda$registerTypeProcessors$19(JvmInstructions.java:183)
	at me.darknet.assembler.instructions.Instruction.transform(Instruction.java:43)
	at me.darknet.assembler.ast.specific.ASTMethod.accept(ASTMethod.java:79)
	at me.darknet.assembler.transformer.Transformer.transform(Transformer.java:41)
	at me.darknet.assembler.compile.JvmCompiler.compile(JvmCompiler.java:91)
	at software.coley.recaf.services.assembler.AbstractAssemblerPipeline.compile(AbstractAssemblerPipeline.java:120)
	at software.coley.recaf.services.assembler.JvmAssemblerPipeline.assemble(JvmAssemblerPipeline.java:73)
	at software.coley.recaf.services.assembler.JvmAssemblerPipeline$Proxy$_$$_WeldClientProxy.assemble(Unknown Source)
	at software.coley.recaf.ui.pane.editing.assembler.AssemblerPane.lambda$assemble$31(AssemblerPane.java:405)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Note:** similar isn's like instanceof, anewarray and multianewarray should be checked too.

**Comment by Col-E** [comment]
upstream: b3a226c50f94e082fa9cf6e28f4d9be207f83f28
