### ISSUE TITLE
NullPointerException when open History window

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#84]
### Steps to reproduce
1. Open Recaf
2. Do nothing
3. Click `History` -> `View states`

### Stacktrace
```
Exception in thread "JavaFX Application Thread" java.lang.ExceptionInInitializerError
	at me.coley.recaf.ui.FxWindow.lambda$start$6(FxWindow.java:49)
	at me.coley.recaf.ui.component.ActionMenuItem.lambda$new$0(ActionMenuItem.java:13)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	...
Caused by: java.lang.NullPointerException
	at me.coley.recaf.ui.FxHistory.updateList(FxHistory.java:119)
	at me.coley.recaf.ui.FxHistory.<init>(FxHistory.java:94)
	at me.coley.recaf.ui.FxHistory.<clinit>(FxHistory.java:41)
	... 44 more
```

---

### Possible solutions
Give [Input#current](../blob/7d8ae836e5ffc4e12fd62f394f3fbfcbe7fa7ea1/src/me/coley/recaf/Input.java#L1277) an initial value, or add something like
```diff
diff --git a/src/me/coley/recaf/ui/FxHistory.java b/src/me/coley/recaf/ui/FxHistory.java
index 7eaa9d0..d48ff88 100644
--- a/src/me/coley/recaf/ui/FxHistory.java
+++ b/src/me/coley/recaf/ui/FxHistory.java
@@ -116,7 +116,8 @@ public class FxHistory extends Stage {

        private void updateList() {
                histories.getItems().clear();
-               histories.getItems().addAll(Input.get().getHistory().values());
+               Input input = Input.get();
+               if (input != null) histories.getItems().addAll(input.getHistory().values());
        }

        private void updateSelected(Collection<String> classes) {
```

**Comment by Col-E** [comment]
The history menu option could also be disabled until a current input is specified.
