### ISSUE TITLE
`instanceof` expects invalid representation and silently fails on correct representation

### ISSUE THREAD

**Issue by C0D3-M4513R** [Col-E/Recaf#841]
**Describe the bug**

> A clear and concise description of what the bug is.

**To Reproduce**
1. Add a class `L`
2. Add the following bytecode and save.
3. Saving succeeds, except it doesn't actually and an error is thrown in the console

```
.method static test ()V {
	code: {
		iconst_0
		anewarray LL;
		instanceof L
	}
}
```

for `anewarray LL;` see #840

If applicable, add the exception/stacktrace.
```
13:41:10.937 [AssemblerPane/ForkJoinPool.commonPool-worker-7] ERROR: Uncaught exception when assembling contents of JVM class: L
java.lang.IllegalStateException: Expected InstanceType
	at dev.xdark.blw.type.TypeReader.read(TypeReader.java:42)
	at me.darknet.assembler.compile.visitor.BlwCodeVisitor.visitTypeInsn(BlwCodeVisitor.java:264)
	at me.darknet.assembler.instructions.jvm.JvmInstructions.lambda$registerTypeProcessors$19(JvmInstructions.java:183)
	at me.darknet.assembler.instructions.Instruction.transform(Instruction.java:43)
	at me.darknet.assembler.ast.specific.ASTMethod.accept(ASTMethod.java:79)
	at me.darknet.assembler.ast.specific.ASTClass.accept(ASTClass.java:172)
	at me.darknet.assembler.transformer.Transformer.transform(Transformer.java:43)
	at me.darknet.assembler.compile.JvmCompiler.compile(JvmCompiler.java:91)
	at software.coley.recaf.services.assembler.AbstractAssemblerPipeline.compile(AbstractAssemblerPipeline.java:120)
	at software.coley.recaf.services.assembler.JvmAssemblerPipeline.assemble(JvmAssemblerPipeline.java:73)
	at software.coley.recaf.services.assembler.JvmAssemblerPipeline$Proxy$_$$_WeldClientProxy.assemble(Unknown Source)
	at software.coley.recaf.ui.pane.editing.assembler.AssemblerPane.lambda$assemble$31(AssemblerPane.java:405)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Comment by Col-E** [comment]
upstream: 06e5b2c3cef4f1c6219822cc82f28f8dcb88c403
