### ISSUE TITLE
`multianewarray` without an array type fails silently

### ISSUE THREAD

**Issue by C0D3-M4513R** [Col-E/Recaf#842]
**Describe the bug**

> A clear and concise description of what the bug is.

**To Reproduce**

1. Add a class `L`
2. Add the following bytecode
3. There will be an exception in the console before you even save
4. Saving will appear to succeed, but on the console there will be an exception instead

```
.method static test ()V {
	code: {
		multianewarray LL; 0
                pop
	}
}
```

**Exception**

If applicable, add the exception/stacktrace.
```
13:45:25.839 [AssemblerPane/ForkJoinPool.commonPool-worker-18] ERROR: Uncaught exception when assembling contents of JVM class: L
java.lang.IllegalStateException: Expected ArrayType
	at dev.xdark.blw.type.Types.arrayTypeFromDescriptor(Types.java:82)
	at me.darknet.assembler.compile.visitor.BlwCodeVisitor.visitMultiANewArrayInsn(BlwCodeVisitor.java:359)
	at me.darknet.assembler.instructions.jvm.JvmInstructions.lambda$registerInstructions$7(JvmInstructions.java:95)
	at me.darknet.assembler.instructions.Instruction.transform(Instruction.java:43)
	at me.darknet.assembler.ast.specific.ASTMethod.accept(ASTMethod.java:79)
	at me.darknet.assembler.ast.specific.ASTClass.accept(ASTClass.java:172)
	at me.darknet.assembler.transformer.Transformer.transform(Transformer.java:43)
	at me.darknet.assembler.compile.JvmCompiler.compile(JvmCompiler.java:91)
	at software.coley.recaf.services.assembler.AbstractAssemblerPipeline.compile(AbstractAssemblerPipeline.java:120)
	at software.coley.recaf.services.assembler.JvmAssemblerPipeline.assemble(JvmAssemblerPipeline.java:73)
	at software.coley.recaf.services.assembler.JvmAssemblerPipeline$Proxy$_$$_WeldClientProxy.assemble(Unknown Source)
	at software.coley.recaf.ui.pane.editing.assembler.AssemblerPane.lambda$assemble$31(AssemblerPane.java:405)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

**Comment by Col-E** [comment]
upstream: f61f0e58138d880f3c33e7b0ce4966c78e011f40
