### ISSUE TITLE
Cannot save file with modifications

### ISSUE THREAD

**Issue by Pseudow** [Col-E/Recaf#845]
**Describe the bug**
I can't modify classes and then let recaf recompile it.

**To Reproduce**
```
14:17:51.449 [ForkJoinPool-1-worker-2] ERROR: Failed to analyze phantom references for primary resource
java.lang.IllegalStateException: null
        at org.clyze.jphantom.methods.MethodLookupTable$CachingAdapter.visit(MethodLookupTable.java:74)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.clyze.jphantom.adapters.SuperclassAdapter.visit(SuperclassAdapter.java:27)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.clyze.jphantom.adapters.InterfaceAdder.visit(InterfaceAdder.java:30)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.clyze.jphantom.adapters.SuperclassAdapter.visit(SuperclassAdapter.java:27)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.clyze.jphantom.adapters.InterfaceAdder.visit(InterfaceAdder.java:30)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:570)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:425)
        at org.clyze.jphantom.Transformer.transform(Transformer.java:53)
        at org.clyze.jphantom.Phantoms.generateClasses(Phantoms.java:57)
        at org.clyze.jphantom.JPhantom.run(JPhantom.java:116)
        at me.coley.recaf.workspace.PhantomResource.populatePhantoms(PhantomResource.java:105)
        at me.coley.recaf.workspace.Workspace.lambda$analyzePhantoms$0(Workspace.java:160)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
14:19:17.091 [JavaFX Application Thread] WARN : Line 42, Col 85: cannot find symbol
```

**Screenshots**

![image](https://github.com/user-attachments/assets/79cc60fe-cc19-4802-8f0c-1c319945769f)

even if I add the librairies it won't recognized them as well as the jdk.

**Comment by Col-E** [comment]
1. This looks like you're using 2.X
2. The JPhantom error can be ignored if you don't intent to use recompile for decompiled code
3. If recompiling fails, use the assembler
4. The compiler says you're trying to call a method which does not exist, that's subject to the quality of the decompilation. You can try changing decompilers for different results but otherwise its not our responsibility to ensure the code is perfectly recompilable.

**Comment by Pseudow** [comment]
Yes Im currently using the last version 2.21.4, but whats weird is that the method is a java standard library method from java.util.Map, and yes I have already thought about using Krakatau to disemble my code but its much harder

**Comment by xxDark** [comment]
You can't add JDK as a library. You have to start Recaf with JDK9+ for `Map.entry` method to be recognizable.
