### ISSUE TITLE
Recaf crash

### ISSUE THREAD

**Issue by meiMingle** [Col-E/Recaf#867]
Diagnostics:
```
01:08:41.695 [AccessPatcher/main] DEBUG: Opening access to all packages
01:08:41.709 [AccessPatcher/main] DEBUG: Patching package reflection restrictions
01:08:41.821 [JFXValidation/main] INFO : JavaFX successfully initialized: 24-ea
01:08:41.822 [Bootstrap/main] INFO : Initializing Recaf 4.0.0-SNAPSHOT
 - Build rev:  1
 - Build date: 2024 10/19 22:10
 - Build hash: de2138caef7255fc941ccec8b58b0345310ad9db
01:08:41.822 [Bootstrap/main] INFO : Creating Recaf CDI container...
01:08:41.826 [Bootstrap/main] INFO : CDI: Adding interceptors & extensions
01:08:41.827 [Bootstrap/main] INFO : CDI: Registering bean packages
01:08:41.828 [Bootstrap/main] INFO : CDI: Running user-defined Consumer<Weld>
01:08:41.828 [Bootstrap/main] INFO : CDI: Initializing...
01:08:42.730 [Bootstrap/main] ERROR: Failed to create Recaf CDI container
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type BundleIconProviderFactory with qualifiers @Default
  at injection point [BackedAnnotatedParameter] Parameter 14 of [BackedAnnotatedConstructor] @Inject public software.coley.recaf.services.cell.icon.IconProviderService(@Nonnull IconProviderServiceConfig, @Nonnull ClassIconProviderFactory, @Nonnull FileIconProviderFactory, @Nonnull InnerClassIconProviderFactory, @Nonnull FieldIconProviderFactory, @Nonnull MethodIconProviderFactory, @Nonnull InstructionIconProviderFactory, @Nonnull ThrowsIconProviderFactory, @Nonnull CatchIconProviderFactory, @Nonnull VariableIconProviderFactory, @Nonnull AnnotationIconProviderFactory, @Nonnull PackageIconProviderFactory, @Nonnull DirectoryIconProviderFactory, @Nonnull BundleIconProviderFactory, @Nonnull ResourceIconProviderFactory)
  at software.coley.recaf.services.cell.icon.IconProviderService.<init>(IconProviderService.java:0)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:379)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:294)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:141)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:163)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:534)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:65)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at org.jboss.weld.executor.CommonForkJoinPoolExecutorServices.lambda$wrap$0(CommonForkJoinPoolExecutorServices.java:70)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedInterruptibleCallable.compute(ForkJoinTask.java:1689)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Exit code: 150
Java
 - Version (Runtime): 22.0.1+8
 - Version (Raw):     22
 - Vendor:            Azul Systems, Inc.
 - Home:              C:\Users\Maria\.jdks\zulu22.30.13-ca-jdk22.0.1-win_x64
JavaFX
 - Version (Runtime): 24-ea+5
 - Version (Raw):     24-ea
Operating System
 - Name:           Windows 10
 - Version:        10.0
 - Architecture:   amd64
 - Processors:     8
 - Path Separator: ;
Recaf
 - Version:    4.0.0-SNAPSHOT
 - Build hash: de2138caef7255fc941ccec8b58b0345310ad9db
 - Build date: 2024 10/19 22:10
Launch
 - Args: software.coley.recaf.Main
Classpath:
 - File: recaf.jar
   - SHA1: 6c43d0b96c2e07ce086cbe5f1db160b1e37dfee5
 - File: dependencies\javafx-base-24-ea+5-win.jar
   - SHA1: d07c520a72cf5ab03666bf5e101d9089646f8624
Threads
 - ForkJoinPool.commonPool-worker-4 [WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:2145)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2036)
   - java.base@22.0.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
 - Attach Listener [RUNNABLE]
 - ForkJoinPool.commonPool-worker-6 [TIMED_WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:2145)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2036)
   - java.base@22.0.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
 - main [RUNNABLE]
   - java.base@22.0.1/java.lang.Thread.dumpThreads(Native Method)
   - java.base@22.0.1/java.lang.Thread.getAllStackTraces(Thread.java:2488)
   - app//software.coley.recaf.ExitDebugLoggingHook.handle(ExitDebugLoggingHook.java:189)
   - app//software.coley.recaf.ExitDebugLoggingHook.run(ExitDebugLoggingHook.java:67)
   - app//software.coley.recaf.ExitDebugLoggingHook$$Lambda/0x000002a9360f5028.run(Unknown Source)
   - java.base@22.0.1/java.lang.Shutdown.runHooks(Shutdown.java:130)
   - java.base@22.0.1/java.lang.Shutdown.exit(Shutdown.java:167)
   - java.base@22.0.1/java.lang.Runtime.exit(Runtime.java:188)
   - java.base@22.0.1/java.lang.System.exit(System.java:1925)
   - app//software.coley.recaf.ExitDebugLoggingHook.exit(ExitDebugLoggingHook.java:218)
   - app//software.coley.recaf.Bootstrap.get(Bootstrap.java:48)
   - app//software.coley.recaf.Main.main(Main.java:84)
 - ForkJoinPool.commonPool-worker-1 [WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:2145)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2036)
   - java.base@22.0.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
 - ForkJoinPool.commonPool-worker-2 [WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:2145)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2036)
   - java.base@22.0.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
 - weld-preloader-6 [WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4013)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3961)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
   - java.base@22.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   - java.base@22.0.1/java.lang.Thread.runWith(Thread.java:1583)
   - java.base@22.0.1/java.lang.Thread.run(Thread.java:1570)
 - Reference Handler [RUNNABLE]
   - java.base@22.0.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
   - java.base@22.0.1/java.lang.ref.Reference.processPendingReferences(Reference.java:246)
   - java.base@22.0.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:208)
 - Finalizer [WAITING]
   - java.base@22.0.1/java.lang.Object.wait0(Native Method)
   - java.base@22.0.1/java.lang.Object.wait(Object.java:375)
   - java.base@22.0.1/java.lang.Object.wait(Object.java:348)
   - java.base@22.0.1/java.lang.ref.NativeReferenceQueue.await(NativeReferenceQueue.java:48)
   - java.base@22.0.1/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158)
   - java.base@22.0.1/java.lang.ref.NativeReferenceQueue.remove(NativeReferenceQueue.java:89)
   - java.base@22.0.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
 - ForkJoinPool.commonPool-worker-7 [WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:2145)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2036)
   - java.base@22.0.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
 - ForkJoinPool.commonPool-worker-5 [WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:2145)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2036)
   - java.base@22.0.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
 - ForkJoinPool.commonPool-worker-3 [WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:2145)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2036)
   - java.base@22.0.1/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
 - weld-preloader-5 [WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4013)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3961)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
   - java.base@22.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   - java.base@22.0.1/java.lang.Thread.runWith(Thread.java:1583)
   - java.base@22.0.1/java.lang.Thread.run(Thread.java:1570)
 - weld-preloader-1 [WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4013)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3961)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
   - java.base@22.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   - java.base@22.0.1/java.lang.Thread.runWith(Thread.java:1583)
   - java.base@22.0.1/java.lang.Thread.run(Thread.java:1570)
 - weld-preloader-4 [WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4013)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3961)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
   - java.base@22.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   - java.base@22.0.1/java.lang.Thread.runWith(Thread.java:1583)
   - java.base@22.0.1/java.lang.Thread.run(Thread.java:1570)
 - Notification Thread [RUNNABLE]
 - Common-Cleaner [TIMED_WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847)
   - java.base@22.0.1/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:71)
   - java.base@22.0.1/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:143)
   - java.base@22.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:218)
   - java.base@22.0.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
   - java.base@22.0.1/java.lang.Thread.runWith(Thread.java:1583)
   - java.base@22.0.1/java.lang.Thread.run(Thread.java:1570)
   - java.base@22.0.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
 - weld-preloader-7 [WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4013)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3961)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
   - java.base@22.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   - java.base@22.0.1/java.lang.Thread.runWith(Thread.java:1583)
   - java.base@22.0.1/java.lang.Thread.run(Thread.java:1570)
 - Signal Dispatcher [RUNNABLE]
 - weld-preloader-2 [WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4013)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3961)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
   - java.base@22.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   - java.base@22.0.1/java.lang.Thread.runWith(Thread.java:1583)
   - java.base@22.0.1/java.lang.Thread.run(Thread.java:1570)
 - weld-preloader-3 [WAITING]
   - java.base@22.0.1/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:4013)
   - java.base@22.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3961)
   - java.base@22.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
   - java.base@22.0.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   - java.base@22.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
   - java.base@22.0.1/java.lang.Thread.runWith(Thread.java:1583)
   - java.base@22.0.1/java.lang.Thread.run(Thread.java:1570)

```

**Comment by meiMingle** [comment]
This error occurred due to an unstable network that caused incomplete download of JavaFX related dependencies.
