### ISSUE TITLE
Recaf crash

### ISSUE THREAD

**Issue by dandud100** [Col-E/Recaf#868]
Diagnostics:
```

17:17:29.379 [AccessPatcher/main] DEBUG: Opening access to all packages
17:17:29.395 [AccessPatcher/main] DEBUG: Patching package reflection restrictions
17:17:29.516 [JFXValidation/main] INFO : JavaFX successfully initialized: 24-ea
17:17:29.517 [Bootstrap/main] INFO : Initializing Recaf 4.0.0-SNAPSHOT
 - Build rev:  1
 - Build date: 2024 10/19 22:10
 - Build hash: de2138caef7255fc941ccec8b58b0345310ad9db
17:17:29.518 [Bootstrap/main] INFO : Creating Recaf CDI container...
17:17:29.521 [Bootstrap/main] INFO : CDI: Adding interceptors & extensions
17:17:29.522 [Bootstrap/main] INFO : CDI: Registering bean packages
17:17:29.522 [Bootstrap/main] INFO : CDI: Running user-defined Consumer<Weld>
17:17:29.523 [Bootstrap/main] INFO : CDI: Initializing...
17:17:31.098 [Bootstrap/main] ERROR: Failed to create Recaf CDI container
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type AttachManager with qualifiers @Default
  at injection point [BackedAnnotatedParameter] Parameter 2 of [BackedAnnotatedConstructor] @Inject public software.coley.recaf.ui.window.RemoteVirtualMachinesWindow(@Nonnull RemoteVirtualMachinesPane, @Nonnull AttachManager, @Nonnull AttachManagerConfig)
  at software.coley.recaf.ui.window.RemoteVirtualMachinesWindow.<init>(RemoteVirtualMachinesWindow.java:0)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:379)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:294)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:141)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:163)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:534)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:65)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at org.jboss.weld.executor.CommonForkJoinPoolExecutorServices.lambda$wrap$0(CommonForkJoinPoolExecutorServices.java:70)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedInterruptibleCallable.compute(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Exit code: 150
Java
 - Version (Runtime): 22.0.2+9
 - Version (Raw):     22
 - Vendor:            Eclipse Adoptium
 - Home:              C:\Program Files\Eclipse Adoptium\jre-22.0.2.9-hotspot
JavaFX
 - Version (Runtime): 24-ea+5
 - Version (Raw):     24-ea
Operating System
 - Name:           Windows 11
 - Version:        10.0
 - Architecture:   amd64
 - Processors:     16
 - Path Separator: ;
Recaf
 - Version:    4.0.0-SNAPSHOT
 - Build hash: de2138caef7255fc941ccec8b58b0345310ad9db
 - Build date: 2024 10/19 22:10
Launch
 - Args: software.coley.recaf.Main
Classpath:
 - File: recaf.jar
   - SHA1: 6c43d0b96c2e07ce086cbe5f1db160b1e37dfee5
 - File: dependencies\javafx-base-24-ea+5-win.jar
   - SHA1: d07c520a72cf5ab03666bf5e101d9089646f8624
 - File: dependencies\javafx-controls-24-ea+5-win.jar
   - SHA1: b2b19af5eaf924723ac91eb649e446d11e2ee75c
 - File: dependencies\javafx-graphics-24-ea+5-win.jar
   - SHA1: f7ea890966a9a5578c3de6edac9b724ef283d72f
 - File: dependencies\javafx-media-24-ea+5-win.jar
   - SHA1: 835616954398a8494615cad521236338ad3a2b94
Threads
 - Notification Thread [RUNNABLE]
 - weld-preloader-15 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-13 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - Attach Listener [RUNNABLE]
 - weld-preloader-5 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-14 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - weld-preloader-4 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-10 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-15 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - weld-preloader-9 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-7 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - weld-preloader-10 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-8 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - weld-preloader-7 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - weld-preloader-11 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - Common-Cleaner [TIMED_WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.lang.ref.ReferenceQueue.await(Unknown Source)
   - java.base@22.0.2/java.lang.ref.ReferenceQueue.remove0(Unknown Source)
   - java.base@22.0.2/java.lang.ref.ReferenceQueue.remove(Unknown Source)
   - java.base@22.0.2/jdk.internal.ref.CleanerImpl.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
   - java.base@22.0.2/jdk.internal.misc.InnocuousThread.run(Unknown Source)
 - weld-preloader-14 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-1 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - weld-preloader-8 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - weld-preloader-2 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-9 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - Signal Dispatcher [RUNNABLE]
 - ForkJoinPool.commonPool-worker-12 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-3 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-6 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - weld-preloader-12 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - Reference Handler [RUNNABLE]
   - java.base@22.0.2/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
   - java.base@22.0.2/java.lang.ref.Reference.processPendingReferences(Unknown Source)
   - java.base@22.0.2/java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)
 - weld-preloader-6 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - main [RUNNABLE]
   - java.base@22.0.2/java.lang.Thread.dumpThreads(Native Method)
   - java.base@22.0.2/java.lang.Thread.getAllStackTraces(Unknown Source)
   - app//software.coley.recaf.ExitDebugLoggingHook.handle(ExitDebugLoggingHook.java:189)
   - app//software.coley.recaf.ExitDebugLoggingHook.run(ExitDebugLoggingHook.java:67)
   - app//software.coley.recaf.ExitDebugLoggingHook$$Lambda/0x0000021b280edcb8.run(Unknown Source)
   - java.base@22.0.2/java.lang.Shutdown.runHooks(Unknown Source)
   - java.base@22.0.2/java.lang.Shutdown.exit(Unknown Source)
   - java.base@22.0.2/java.lang.Runtime.exit(Unknown Source)
   - java.base@22.0.2/java.lang.System.exit(Unknown Source)
   - app//software.coley.recaf.ExitDebugLoggingHook.exit(ExitDebugLoggingHook.java:218)
   - app//software.coley.recaf.Bootstrap.get(Bootstrap.java:48)
   - app//software.coley.recaf.Main.main(Main.java:84)
 - Finalizer [WAITING]
   - java.base@22.0.2/java.lang.Object.wait0(Native Method)
   - java.base@22.0.2/java.lang.Object.wait(Unknown Source)
   - java.base@22.0.2/java.lang.Object.wait(Unknown Source)
   - java.base@22.0.2/java.lang.ref.NativeReferenceQueue.await(Unknown Source)
   - java.base@22.0.2/java.lang.ref.ReferenceQueue.remove0(Unknown Source)
   - java.base@22.0.2/java.lang.ref.NativeReferenceQueue.remove(Unknown Source)
   - java.base@22.0.2/java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-11 [TIMED_WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - weld-preloader-3 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - weld-preloader-1 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-2 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - weld-preloader-13 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.park(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.runWith(Unknown Source)
   - java.base@22.0.2/java.lang.Thread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-4 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
 - ForkJoinPool.commonPool-worker-5 [WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.awaitWork(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   - java.base@22.0.2/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

```

**Comment by Col-E** [comment]
From the report you are running from a JRE and not a JDK. We rely on a number of modules in the JDK and it looks like we just crash if you run it from a JRE instead. I'll go ahead and make the user-feedback for this problem more clear. I've updated the launcher to explicitly handle this problem.

Just re-run the launcher and specify a JDK as your Java version to run Recaf with and you'll be good to go 👍
