### ISSUE TITLE
Recaf crash

### ISSUE THREAD

**Issue by elox1k** [Col-E/Recaf#872]
Diagnostics:
```

JavaFX has missing classes

00:05:08.133 [AccessPatcher/main] DEBUG: Opening access to all packages
00:05:08.148 [AccessPatcher/main] DEBUG: Patching package reflection restrictions
00:05:08.231 [JFXValidation/main] ERROR: JFX validation failed, could not find 'VersionInfo' class
java.lang.ClassNotFoundException: com.sun.javafx.runtime.VersionInfo
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:413)
	at java.base/java.lang.Class.forName(Class.java:404)
	at software.coley.recaf.util.JFXValidation.validateJFX(JFXValidation.java:26)
	at software.coley.recaf.Main.main(Main.java:77)
Exit code: 101
Java
 - Version (Runtime): 22.0.2+9-70
 - Version (Raw):     22
 - Vendor:            Oracle Corporation
 - Home:              C:\Program Files\Java\jdk-22.0.2
JavaFX
 - Version (Runtime): <uninitialized>
 - Version (Raw):     <uninitialized>
Operating System
 - Name:           Windows 10
 - Version:        10.0
 - Architecture:   amd64
 - Processors:     12
 - Path Separator: ;
Recaf
 - Version:    4.0.0-SNAPSHOT
 - Build hash: 4a58d98b712c626e9ecb4c5a38b37a7a5e2a8432
 - Build date: 2024 11/02 05:00
Launch
 - Args: software.coley.recaf.Main
Classpath:
 - File: recaf.jar
   - SHA1: 0e880b788b77f7c346c79d9b5a9281c6622e5335
Threads
 - Notification Thread [RUNNABLE]
 - Reference Handler [RUNNABLE]
   - java.base@22.0.2/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
   - java.base@22.0.2/java.lang.ref.Reference.processPendingReferences(Reference.java:246)
   - java.base@22.0.2/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:208)
 - Signal Dispatcher [RUNNABLE]
 - main [RUNNABLE]
   - java.base@22.0.2/java.lang.Thread.dumpThreads(Native Method)
   - java.base@22.0.2/java.lang.Thread.getAllStackTraces(Thread.java:2489)
   - app//software.coley.recaf.ExitDebugLoggingHook.handle(ExitDebugLoggingHook.java:191)
   - app//software.coley.recaf.ExitDebugLoggingHook.run(ExitDebugLoggingHook.java:67)
   - app//software.coley.recaf.ExitDebugLoggingHook$$Lambda/0x0000016b360f5028.run(Unknown Source)
   - java.base@22.0.2/java.lang.Shutdown.runHooks(Shutdown.java:130)
   - java.base@22.0.2/java.lang.Shutdown.exit(Shutdown.java:167)
   - java.base@22.0.2/java.lang.Runtime.exit(Runtime.java:188)
   - java.base@22.0.2/java.lang.System.exit(System.java:1925)
   - app//software.coley.recaf.ExitDebugLoggingHook.exit(ExitDebugLoggingHook.java:220)
   - app//software.coley.recaf.Main.main(Main.java:79)
 - Attach Listener [RUNNABLE]
 - Finalizer [WAITING]
   - java.base@22.0.2/java.lang.Object.wait0(Native Method)
   - java.base@22.0.2/java.lang.Object.wait(Object.java:375)
   - java.base@22.0.2/java.lang.Object.wait(Object.java:348)
   - java.base@22.0.2/java.lang.ref.NativeReferenceQueue.await(NativeReferenceQueue.java:48)
   - java.base@22.0.2/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158)
   - java.base@22.0.2/java.lang.ref.NativeReferenceQueue.remove(NativeReferenceQueue.java:89)
   - java.base@22.0.2/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
 - Common-Cleaner [TIMED_WAITING]
   - java.base@22.0.2/jdk.internal.misc.Unsafe.park(Native Method)
   - java.base@22.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
   - java.base@22.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847)
   - java.base@22.0.2/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:71)
   - java.base@22.0.2/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:143)
   - java.base@22.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:218)
   - java.base@22.0.2/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
   - java.base@22.0.2/java.lang.Thread.runWith(Thread.java:1583)
   - java.base@22.0.2/java.lang.Thread.run(Thread.java:1570)
   - java.base@22.0.2/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)

```

**Comment by Col-E** [comment]
You need to download JavaFX:

![image](https://github.com/user-attachments/assets/ef568cf0-1fe6-434b-8fef-9a69505dcaf5)

It's the 2nd button in the launcher GUI.
