### ISSUE TITLE
Phantom analysis encountered an exception.

### ISSUE THREAD

**Issue by meiMingle** [Col-E/Recaf#886]
[demo.zip](https://github.com/user-attachments/files/17894488/demo.zip)
![image](https://github.com/user-attachments/assets/63b22e4f-187c-46b9-88e9-4fd0105df3fa)
> 02:39:00.706 [JPhantomGenerator/ForkJoinPool.commonPool-worker-6] ERROR: Phantom analysis encountered an exception.
java.lang.StackOverflowError: null
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
        at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
 

Due to the length limit of comments on GitHub, some repeated stack logs are omitted here

**Comment by meiMingle** [comment]
Pwd of attachment: Reacf

**Comment by Col-E** [comment]
#707 - Closed with this
