### ISSUE TITLE
Recaf 4.x doesn't run on Wayland/Hyprland

### ISSUE THREAD

**Issue by micartey** [Col-E/Recaf#898]
Diagnostics:
```
Dec 28, 2024 7:33:16 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @27808f31'
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /home/daniel/.openjfx/cache/24-ea+19/amd64/libprism_es2.so: libX11.so.6: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /home/daniel/.openjfx/cache/24-ea+19/amd64/libprism_es2.so: libX11.so.6: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2402)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2028)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:212)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:192)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:134)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:55)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:59)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:462)
	at java.base/java.lang.Class.forName(Class.java:453)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:88)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:121)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Loading library glass from resource failed: java.lang.UnsatisfiedLinkError: /home/daniel/.openjfx/cache/24-ea+19/amd64/libglass.so: libX11.so.6: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /home/daniel/.openjfx/cache/24-ea+19/amd64/libglass.so: libX11.so.6: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2402)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2028)
	at com.sun.glass.utils.NativeLibLoader.installLibraryFromResource(NativeLibLoader.java:212)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryFromResource(NativeLibLoader.java:192)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:134)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:55)
	at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:109)
	at com.sun.glass.ui.Application.loadNativeLibrary(Application.java:117)
	at com.sun.glass.ui.gtk.GtkApplication.<clinit>(GtkApplication.java:83)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:40)
	at com.sun.glass.ui.Application.run(Application.java:143)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:284)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:276)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:154)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:652)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:672)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$0(LauncherImpl.java:197)
	at java.base/java.lang.Thread.run(Thread.java:1575)


```

**Comment by Col-E** [comment]
> `libX11.so.6: cannot open shared object file`

JavaFX relies on X11 so if that isn't in your environment it won't link/run.
