### ISSUE TITLE
Unable to load glass GTK library.

### ISSUE THREAD

**Issue by siddhsql** [Col-E/Recaf#899]
**Describe the bug**

> A clear and concise description of what the bug is.

**To Reproduce**

Launch recaf. I am using WSL (Windows Subsystem for Linux) if it matters.

**Exception**

If applicable, add the exception/stacktrace.

```
$ /home/siddjain/jdk-23.0.1/bin/java -jar bin/recaf-gui-0.8.1.jar
Looking in '/home/siddjain/.config/Recaf' for Recaf/dependencies...
Using cached version of JavaFX: 24-ea+19
Running Recaf '4.0.0-SNAPSHOT' with JavaFX '24-ea+19:linux'
Receiving classpath entries from parent process...
Resolving Recaf entry-point...
Launching Recaf...
11:10:18.464 [AccessPatcher/main] DEBUG: Opening access to all packages
11:10:18.489 [AccessPatcher/main] DEBUG: Patching package reflection restrictions
11:10:18.634 [JFXValidation/main] INFO : JavaFX successfully initialized: 24-ea
11:10:18.638 [Bootstrap/main] INFO : Initializing Recaf 4.0.0-SNAPSHOT
 - Build rev:  1
 - Build date: 2024 12/11 03:14
 - Build hash: 483b8004251e5c654090d2315af30913d724a083
11:10:18.638 [Bootstrap/main] INFO : Creating Recaf CDI container...
11:10:18.649 [Bootstrap/main] INFO : CDI: Adding interceptors & extensions
11:10:18.651 [Bootstrap/main] INFO : CDI: Registering bean packages
11:10:18.652 [Bootstrap/main] INFO : CDI: Running user-defined Consumer<Weld>
11:10:18.653 [Bootstrap/main] INFO : CDI: Initializing...
11:10:20.331 [Bootstrap/main] INFO : Recaf CDI container created in 1693ms
11:10:20.354 [Main/main] TRACE: Compressing 1 old log files
11:10:20.383 [Lang/main] DEBUG: Found 6 translations
11:10:20.405 [Lang/main] INFO : Loaded translations 'cs_CZ'
11:10:20.414 [Lang/main] INFO : Loaded translations 'pl_PL'
11:10:20.422 [Lang/main] INFO : Loaded translations 'sv_SE'
11:10:20.431 [Lang/main] INFO : Loaded translations 'en_US'
11:10:20.439 [Lang/main] INFO : Loaded translations 'zh_CN'
11:10:20.441 [Lang/main] INFO : Loaded translations 'de_DE'
11:10:20.474 [Main/main] INFO : Initialization: No plugins found
Dec 30, 2024 11:10:20 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @37d31475'
11:10:21.288 [Main/main] ERROR: Uncaught exception on thread 'main'
java.lang.UnsupportedOperationException: Unable to load glass GTK library.
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:162)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:40)
        at com.sun.glass.ui.Application.run(Application.java:143)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:284)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:276)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:154)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:652)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:672)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$0(LauncherImpl.java:197)
        at java.base/java.lang.Thread.run(Thread.java:1575)
Weld SE container recaf shut down by shutdown hook
Failed launching Recaf: <unknown error>
```

**Screenshots**

**Comment by Col-E** [comment]
Do you have GTK3 in your path?

**Comment by siddhsql** [comment]
i fixed it by installing gtk-3 but now when i export a file the exported
class is not valid. i tried opening it in both jd-gui and cfr and both give
me errors. i followed the steps at
https://github.com/Col-E/Recaf-documentation/blob/master/use-edit-via-decompile.md

**Comment by Col-E** [comment]
You can open a new issue for that, but I'll need more information than _"it has errors"_
