### ISSUE TITLE
NPE while opening any file

### ISSUE THREAD

**Issue by andylizi** [Col-E/Recaf#96]
### Stacktrace
```
java.lang.NullPointerException
	at me.coley.recaf.Input.registerLoadListener(Input.java:678)
	at me.coley.recaf.ui.FxWindow$FilePane.onInputChange(FxWindow.java:834)
	at me.coley.event.EventBus$InvokeWrapper.invoke(EventBus.java:471)
	at me.coley.event.EventBus$Handler.invoke(EventBus.java:299)
	at me.coley.event.EventBus$Handler.post(EventBus.java:263)
	at me.coley.event.EventBus.post(EventBus.java:98)
	at me.coley.event.Bus.post(Bus.java:63)
	at me.coley.recaf.event.NewInputEvent.lambda$call$0(NewInputEvent.java:51)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	...
```

### Steps to reproduce
1. Open any file
2. Aaaannnd... there you have it

### Note
The reason this bug isn't discovered until now is the eventbus [eats up all the exceptions](https://github.com/Col-E/Events/blob/1.2/src/main/java/me/coley/event/Bus.java#L190) produced in listener method silently. I only discovered this because I'm [refactoring Events library](https://github.com/Col-E/Events/pull/4) and tried to test the new version on Recaf, so you can't reproduce it immediately on your environment.

**Comment by Col-E** [comment]
Opps. This can be solved with a simple check in FxWindow to see if Recaf started as an agent. This doesn't break anything since its the last line that would be executed.

**Comment by Col-E** [comment]
Pushed the update in the events repo. Your refactored version can be used by updating the recaf `pom.xml` :+1:
